# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addgroup.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61\x64\x64group.proto\x12\tYrcfAgent\x1a\x0eresponse.proto\"\xbc\x01\n\x0cOsdGroupInfo\x12\x10\n\x08group_id\x18\x01 \x01(\r\x12\x37\n\x0e\x66irst_osd_info\x18\x02 \x01(\x0b\x32\x1f.YrcfAgent.OsdGroupInfo.OsdInfo\x12\x38\n\x0fsecond_osd_info\x18\x03 \x01(\x0b\x32\x1f.YrcfAgent.OsdGroupInfo.OsdInfo\x1a\'\n\x07OsdInfo\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0e\n\x06osd_id\x18\x02 \x01(\t\"\x86\x02\n\x0f\x41\x64\x64GroupRequest\x12\x34\n\x08osd_type\x18\x01 \x01(\x0e\x32\".YrcfAgent.AddGroupRequest.OsdType\x12\x16\n\x0e\x61uto_add_group\x18\x02 \x01(\x08\x12\x13\n\x0bmaster_node\x18\x03 \x01(\r\x12\x12\n\nslave_node\x18\x04 \x01(\r\x12\x10\n\x08group_id\x18\x05 \x01(\r\x12\x11\n\tforce_add\x18\x06 \x01(\x08\x12\x0f\n\x07preview\x18\x07 \x01(\x08\x12\x17\n\x0funique_group_id\x18\x08 \x01(\x08\"-\n\x07OsdType\x12\x10\n\x0cINVALID_TYPE\x10\x00\x12\x07\n\x03MDS\x10\x01\x12\x07\n\x03OSS\x10\x02\"f\n\x10\x41\x64\x64GroupResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes\x12/\n\x0eosd_group_info\x18\x02 \x03(\x0b\x32\x17.YrcfAgent.OsdGroupInfo2Q\n\x08\x41\x64\x64Group\x12\x45\n\x08\x41\x64\x64Group\x12\x1a.YrcfAgent.AddGroupRequest\x1a\x1b.YrcfAgent.AddGroupResponse\"\x00\x62\x06proto3')



_OSDGROUPINFO = DESCRIPTOR.message_types_by_name['OsdGroupInfo']
_OSDGROUPINFO_OSDINFO = _OSDGROUPINFO.nested_types_by_name['OsdInfo']
_ADDGROUPREQUEST = DESCRIPTOR.message_types_by_name['AddGroupRequest']
_ADDGROUPRESPONSE = DESCRIPTOR.message_types_by_name['AddGroupResponse']
_ADDGROUPREQUEST_OSDTYPE = _ADDGROUPREQUEST.enum_types_by_name['OsdType']
OsdGroupInfo = _reflection.GeneratedProtocolMessageType('OsdGroupInfo', (_message.Message,), {

  'OsdInfo' : _reflection.GeneratedProtocolMessageType('OsdInfo', (_message.Message,), {
    'DESCRIPTOR' : _OSDGROUPINFO_OSDINFO,
    '__module__' : 'addgroup_pb2'
    # @@protoc_insertion_point(class_scope:YrcfAgent.OsdGroupInfo.OsdInfo)
    })
  ,
  'DESCRIPTOR' : _OSDGROUPINFO,
  '__module__' : 'addgroup_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.OsdGroupInfo)
  })
_sym_db.RegisterMessage(OsdGroupInfo)
_sym_db.RegisterMessage(OsdGroupInfo.OsdInfo)

AddGroupRequest = _reflection.GeneratedProtocolMessageType('AddGroupRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDGROUPREQUEST,
  '__module__' : 'addgroup_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.AddGroupRequest)
  })
_sym_db.RegisterMessage(AddGroupRequest)

AddGroupResponse = _reflection.GeneratedProtocolMessageType('AddGroupResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDGROUPRESPONSE,
  '__module__' : 'addgroup_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.AddGroupResponse)
  })
_sym_db.RegisterMessage(AddGroupResponse)

_ADDGROUP = DESCRIPTOR.services_by_name['AddGroup']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OSDGROUPINFO._serialized_start=46
  _OSDGROUPINFO._serialized_end=234
  _OSDGROUPINFO_OSDINFO._serialized_start=195
  _OSDGROUPINFO_OSDINFO._serialized_end=234
  _ADDGROUPREQUEST._serialized_start=237
  _ADDGROUPREQUEST._serialized_end=499
  _ADDGROUPREQUEST_OSDTYPE._serialized_start=454
  _ADDGROUPREQUEST_OSDTYPE._serialized_end=499
  _ADDGROUPRESPONSE._serialized_start=501
  _ADDGROUPRESPONSE._serialized_end=603
  _ADDGROUP._serialized_start=605
  _ADDGROUP._serialized_end=686
# @@protoc_insertion_point(module_scope)
