# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import addgroup_pb2 as addgroup__pb2


class AddGroupStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddGroup = channel.unary_unary(
        '/YrcfAgent.AddGroup/AddGroup',
        request_serializer=addgroup__pb2.AddGroupRequest.SerializeToString,
        response_deserializer=addgroup__pb2.AddGroupResponse.FromString,
        )


class AddGroupServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddGroup(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AddGroupServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddGroup': grpc.unary_unary_rpc_method_handler(
          servicer.AddGroup,
          request_deserializer=addgroup__pb2.AddGroupRequest.FromString,
          response_serializer=addgroup__pb2.AddGroupResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'YrcfAgent.AddGroup', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
