# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import agent_pb2 as agent__pb2


class AgentStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ClientStats = channel.unary_stream(
        '/Agent/ClientStats',
        request_serializer=agent__pb2.ClientStatsPara.SerializeToString,
        response_deserializer=agent__pb2.ClientStatsRet.FromString,
        )
    self.GetSlaInfo = channel.unary_stream(
        '/Agent/GetSlaInfo',
        request_serializer=agent__pb2.GetSlaInfoPara.SerializeToString,
        response_deserializer=agent__pb2.GetSlaInfoRet.FromString,
        )
    self.MdsOverview = channel.unary_unary(
        '/Agent/MdsOverview',
        request_serializer=agent__pb2.MdsOverviewPara.SerializeToString,
        response_deserializer=agent__pb2.MdsOverviewRet.FromString,
        )
    self.OssOverview = channel.unary_unary(
        '/Agent/OssOverview',
        request_serializer=agent__pb2.OssOverviewPara.SerializeToString,
        response_deserializer=agent__pb2.OssOverviewRet.FromString,
        )
    self.NodeList = channel.unary_stream(
        '/Agent/NodeList',
        request_serializer=agent__pb2.NodeListPara.SerializeToString,
        response_deserializer=agent__pb2.NodeListRet.FromString,
        )


class AgentServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ClientStats(self, request, context):
    """get client opcounter
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSlaInfo(self, request, context):
    """get sla info
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MdsOverview(self, request, context):
    """get mds overview
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OssOverview(self, request, context):
    """get oss overview
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NodeList(self, request, context):
    """get node list
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AgentServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ClientStats': grpc.unary_stream_rpc_method_handler(
          servicer.ClientStats,
          request_deserializer=agent__pb2.ClientStatsPara.FromString,
          response_serializer=agent__pb2.ClientStatsRet.SerializeToString,
      ),
      'GetSlaInfo': grpc.unary_stream_rpc_method_handler(
          servicer.GetSlaInfo,
          request_deserializer=agent__pb2.GetSlaInfoPara.FromString,
          response_serializer=agent__pb2.GetSlaInfoRet.SerializeToString,
      ),
      'MdsOverview': grpc.unary_unary_rpc_method_handler(
          servicer.MdsOverview,
          request_deserializer=agent__pb2.MdsOverviewPara.FromString,
          response_serializer=agent__pb2.MdsOverviewRet.SerializeToString,
      ),
      'OssOverview': grpc.unary_unary_rpc_method_handler(
          servicer.OssOverview,
          request_deserializer=agent__pb2.OssOverviewPara.FromString,
          response_serializer=agent__pb2.OssOverviewRet.SerializeToString,
      ),
      'NodeList': grpc.unary_stream_rpc_method_handler(
          servicer.NodeList,
          request_deserializer=agent__pb2.NodeListPara.FromString,
          response_serializer=agent__pb2.NodeListRet.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Agent', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
