# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import common.grpc.agent_pb2 as agent__pb2


class AgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClientStats = channel.unary_stream(
                '/Agent/ClientStats',
                request_serializer=agent__pb2.ClientStatsPara.SerializeToString,
                response_deserializer=agent__pb2.ClientStatsRet.FromString,
                )
        self.GetSlaInfo = channel.unary_stream(
                '/Agent/GetSlaInfo',
                request_serializer=agent__pb2.GetSlaInfoPara.SerializeToString,
                response_deserializer=agent__pb2.GetSlaInfoRet.FromString,
                )
        self.MdsOverview = channel.unary_unary(
                '/Agent/MdsOverview',
                request_serializer=agent__pb2.MdsOverviewPara.SerializeToString,
                response_deserializer=agent__pb2.MdsOverviewRet.FromString,
                )
        self.OssOverview = channel.unary_unary(
                '/Agent/OssOverview',
                request_serializer=agent__pb2.OssOverviewPara.SerializeToString,
                response_deserializer=agent__pb2.OssOverviewRet.FromString,
                )
        self.NodeList = channel.unary_stream(
                '/Agent/NodeList',
                request_serializer=agent__pb2.NodeListPara.SerializeToString,
                response_deserializer=agent__pb2.NodeListRet.FromString,
                )


class AgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClientStats(self, request, context):
        """get client opcounter
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSlaInfo(self, request, context):
        """get sla info 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MdsOverview(self, request, context):
        """get mds overview
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OssOverview(self, request, context):
        """get oss overview
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeList(self, request, context):
        """get node list
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClientStats': grpc.unary_stream_rpc_method_handler(
                    servicer.ClientStats,
                    request_deserializer=agent__pb2.ClientStatsPara.FromString,
                    response_serializer=agent__pb2.ClientStatsRet.SerializeToString,
            ),
            'GetSlaInfo': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSlaInfo,
                    request_deserializer=agent__pb2.GetSlaInfoPara.FromString,
                    response_serializer=agent__pb2.GetSlaInfoRet.SerializeToString,
            ),
            'MdsOverview': grpc.unary_unary_rpc_method_handler(
                    servicer.MdsOverview,
                    request_deserializer=agent__pb2.MdsOverviewPara.FromString,
                    response_serializer=agent__pb2.MdsOverviewRet.SerializeToString,
            ),
            'OssOverview': grpc.unary_unary_rpc_method_handler(
                    servicer.OssOverview,
                    request_deserializer=agent__pb2.OssOverviewPara.FromString,
                    response_serializer=agent__pb2.OssOverviewRet.SerializeToString,
            ),
            'NodeList': grpc.unary_stream_rpc_method_handler(
                    servicer.NodeList,
                    request_deserializer=agent__pb2.NodeListPara.FromString,
                    response_serializer=agent__pb2.NodeListRet.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Agent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Agent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClientStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Agent/ClientStats',
            agent__pb2.ClientStatsPara.SerializeToString,
            agent__pb2.ClientStatsRet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSlaInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Agent/GetSlaInfo',
            agent__pb2.GetSlaInfoPara.SerializeToString,
            agent__pb2.GetSlaInfoRet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MdsOverview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Agent/MdsOverview',
            agent__pb2.MdsOverviewPara.SerializeToString,
            agent__pb2.MdsOverviewRet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OssOverview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Agent/OssOverview',
            agent__pb2.OssOverviewPara.SerializeToString,
            agent__pb2.OssOverviewRet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NodeList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Agent/NodeList',
            agent__pb2.NodeListPara.SerializeToString,
            agent__pb2.NodeListRet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
