# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockio.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


#import response_pb2 as response__pb2
from . import response_pb2 as response__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='blockio.proto',
  package='YrcfAgent',
  syntax='proto3',
  serialized_pb=_b('\n\rblockio.proto\x12\tYrcfAgent\x1a\x0eresponse.proto\"\x89\x01\n\rBlockLinkInfo\x12\x0f\n\x07link_id\x18\x01 \x01(\r\x12\x36\n\nblock_type\x18\x02 \x01(\x0e\x32\".YrcfAgent.BlockLinkInfo.BlockType\"/\n\tBlockType\x12\x10\n\x0c\x42LOCK_IMPORT\x10\x00\x12\x10\n\x0c\x42LOCK_EXPORT\x10\x01\"H\n\x13\x41\x64\x64\x42lockLinkRequest\x12\x31\n\x0f\x62lock_link_info\x18\x01 \x01(\x0b\x32\x18.YrcfAgent.BlockLinkInfo\"9\n\x14\x41\x64\x64\x42lockLinkResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes\"H\n\x13\x44\x65lBlockLinkRequest\x12\x31\n\x0f\x62lock_link_info\x18\x01 \x01(\x0b\x32\x18.YrcfAgent.BlockLinkInfo\"9\n\x14\x44\x65lBlockLinkResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes\"\x17\n\x15ListBlockLinksRequest\"i\n\x16ListBlockLinksResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes\x12,\n\nblock_info\x18\x02 \x03(\x0b\x32\x18.YrcfAgent.BlockLinkInfo2\x84\x02\n\x07\x42lockIO\x12W\n\x0eListBlockLinks\x12 .YrcfAgent.ListBlockLinksRequest\x1a!.YrcfAgent.ListBlockLinksResponse0\x01\x12O\n\x0c\x41\x64\x64\x42lockLink\x12\x1e.YrcfAgent.AddBlockLinkRequest\x1a\x1f.YrcfAgent.AddBlockLinkResponse\x12O\n\x0c\x44\x65lBlockLink\x12\x1e.YrcfAgent.DelBlockLinkRequest\x1a\x1f.YrcfAgent.DelBlockLinkResponseb\x06proto3')
  ,
  dependencies=[response__pb2.DESCRIPTOR,])



_BLOCKLINKINFO_BLOCKTYPE = _descriptor.EnumDescriptor(
  name='BlockType',
  full_name='YrcfAgent.BlockLinkInfo.BlockType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BLOCK_IMPORT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLOCK_EXPORT', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=135,
  serialized_end=182,
)
_sym_db.RegisterEnumDescriptor(_BLOCKLINKINFO_BLOCKTYPE)


_BLOCKLINKINFO = _descriptor.Descriptor(
  name='BlockLinkInfo',
  full_name='YrcfAgent.BlockLinkInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='link_id', full_name='YrcfAgent.BlockLinkInfo.link_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_type', full_name='YrcfAgent.BlockLinkInfo.block_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BLOCKLINKINFO_BLOCKTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=182,
)


_ADDBLOCKLINKREQUEST = _descriptor.Descriptor(
  name='AddBlockLinkRequest',
  full_name='YrcfAgent.AddBlockLinkRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='block_link_info', full_name='YrcfAgent.AddBlockLinkRequest.block_link_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=256,
)


_ADDBLOCKLINKRESPONSE = _descriptor.Descriptor(
  name='AddBlockLinkResponse',
  full_name='YrcfAgent.AddBlockLinkResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='YrcfAgent.AddBlockLinkResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=315,
)


_DELBLOCKLINKREQUEST = _descriptor.Descriptor(
  name='DelBlockLinkRequest',
  full_name='YrcfAgent.DelBlockLinkRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='block_link_info', full_name='YrcfAgent.DelBlockLinkRequest.block_link_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=389,
)


_DELBLOCKLINKRESPONSE = _descriptor.Descriptor(
  name='DelBlockLinkResponse',
  full_name='YrcfAgent.DelBlockLinkResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='YrcfAgent.DelBlockLinkResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=448,
)


_LISTBLOCKLINKSREQUEST = _descriptor.Descriptor(
  name='ListBlockLinksRequest',
  full_name='YrcfAgent.ListBlockLinksRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=450,
  serialized_end=473,
)


_LISTBLOCKLINKSRESPONSE = _descriptor.Descriptor(
  name='ListBlockLinksResponse',
  full_name='YrcfAgent.ListBlockLinksResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='YrcfAgent.ListBlockLinksResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_info', full_name='YrcfAgent.ListBlockLinksResponse.block_info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=475,
  serialized_end=580,
)

_BLOCKLINKINFO.fields_by_name['block_type'].enum_type = _BLOCKLINKINFO_BLOCKTYPE
_BLOCKLINKINFO_BLOCKTYPE.containing_type = _BLOCKLINKINFO
_ADDBLOCKLINKREQUEST.fields_by_name['block_link_info'].message_type = _BLOCKLINKINFO
_ADDBLOCKLINKRESPONSE.fields_by_name['result'].message_type = response__pb2._RESMES
_DELBLOCKLINKREQUEST.fields_by_name['block_link_info'].message_type = _BLOCKLINKINFO
_DELBLOCKLINKRESPONSE.fields_by_name['result'].message_type = response__pb2._RESMES
_LISTBLOCKLINKSRESPONSE.fields_by_name['result'].message_type = response__pb2._RESMES
_LISTBLOCKLINKSRESPONSE.fields_by_name['block_info'].message_type = _BLOCKLINKINFO
DESCRIPTOR.message_types_by_name['BlockLinkInfo'] = _BLOCKLINKINFO
DESCRIPTOR.message_types_by_name['AddBlockLinkRequest'] = _ADDBLOCKLINKREQUEST
DESCRIPTOR.message_types_by_name['AddBlockLinkResponse'] = _ADDBLOCKLINKRESPONSE
DESCRIPTOR.message_types_by_name['DelBlockLinkRequest'] = _DELBLOCKLINKREQUEST
DESCRIPTOR.message_types_by_name['DelBlockLinkResponse'] = _DELBLOCKLINKRESPONSE
DESCRIPTOR.message_types_by_name['ListBlockLinksRequest'] = _LISTBLOCKLINKSREQUEST
DESCRIPTOR.message_types_by_name['ListBlockLinksResponse'] = _LISTBLOCKLINKSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BlockLinkInfo = _reflection.GeneratedProtocolMessageType('BlockLinkInfo', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKLINKINFO,
  __module__ = 'blockio_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.BlockLinkInfo)
  ))
_sym_db.RegisterMessage(BlockLinkInfo)

AddBlockLinkRequest = _reflection.GeneratedProtocolMessageType('AddBlockLinkRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDBLOCKLINKREQUEST,
  __module__ = 'blockio_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.AddBlockLinkRequest)
  ))
_sym_db.RegisterMessage(AddBlockLinkRequest)

AddBlockLinkResponse = _reflection.GeneratedProtocolMessageType('AddBlockLinkResponse', (_message.Message,), dict(
  DESCRIPTOR = _ADDBLOCKLINKRESPONSE,
  __module__ = 'blockio_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.AddBlockLinkResponse)
  ))
_sym_db.RegisterMessage(AddBlockLinkResponse)

DelBlockLinkRequest = _reflection.GeneratedProtocolMessageType('DelBlockLinkRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELBLOCKLINKREQUEST,
  __module__ = 'blockio_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.DelBlockLinkRequest)
  ))
_sym_db.RegisterMessage(DelBlockLinkRequest)

DelBlockLinkResponse = _reflection.GeneratedProtocolMessageType('DelBlockLinkResponse', (_message.Message,), dict(
  DESCRIPTOR = _DELBLOCKLINKRESPONSE,
  __module__ = 'blockio_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.DelBlockLinkResponse)
  ))
_sym_db.RegisterMessage(DelBlockLinkResponse)

ListBlockLinksRequest = _reflection.GeneratedProtocolMessageType('ListBlockLinksRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTBLOCKLINKSREQUEST,
  __module__ = 'blockio_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.ListBlockLinksRequest)
  ))
_sym_db.RegisterMessage(ListBlockLinksRequest)

ListBlockLinksResponse = _reflection.GeneratedProtocolMessageType('ListBlockLinksResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTBLOCKLINKSRESPONSE,
  __module__ = 'blockio_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.ListBlockLinksResponse)
  ))
_sym_db.RegisterMessage(ListBlockLinksResponse)



_BLOCKIO = _descriptor.ServiceDescriptor(
  name='BlockIO',
  full_name='YrcfAgent.BlockIO',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=583,
  serialized_end=843,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListBlockLinks',
    full_name='YrcfAgent.BlockIO.ListBlockLinks',
    index=0,
    containing_service=None,
    input_type=_LISTBLOCKLINKSREQUEST,
    output_type=_LISTBLOCKLINKSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddBlockLink',
    full_name='YrcfAgent.BlockIO.AddBlockLink',
    index=1,
    containing_service=None,
    input_type=_ADDBLOCKLINKREQUEST,
    output_type=_ADDBLOCKLINKRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DelBlockLink',
    full_name='YrcfAgent.BlockIO.DelBlockLink',
    index=2,
    containing_service=None,
    input_type=_DELBLOCKLINKREQUEST,
    output_type=_DELBLOCKLINKRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BLOCKIO)

DESCRIPTOR.services_by_name['BlockIO'] = _BLOCKIO

# @@protoc_insertion_point(module_scope)
