# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockio.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common.grpc.response_pb2 as response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rblockio.proto\x12\tYrcfAgent\x1a\x0eresponse.proto\"\x89\x01\n\rBlockLinkInfo\x12\x0f\n\x07link_id\x18\x01 \x01(\r\x12\x36\n\nblock_type\x18\x02 \x01(\x0e\x32\".YrcfAgent.BlockLinkInfo.BlockType\"/\n\tBlockType\x12\x10\n\x0c\x42LOCK_IMPORT\x10\x00\x12\x10\n\x0c\x42LOCK_EXPORT\x10\x01\"H\n\x13\x41\x64\x64\x42lockLinkRequest\x12\x31\n\x0f\x62lock_link_info\x18\x01 \x01(\x0b\x32\x18.YrcfAgent.BlockLinkInfo\"9\n\x14\x41\x64\x64\x42lockLinkResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes\"H\n\x13\x44\x65lBlockLinkRequest\x12\x31\n\x0f\x62lock_link_info\x18\x01 \x01(\x0b\x32\x18.YrcfAgent.BlockLinkInfo\"9\n\x14\x44\x65lBlockLinkResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes\"\x17\n\x15ListBlockLinksRequest\"i\n\x16ListBlockLinksResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes\x12,\n\nblock_info\x18\x02 \x03(\x0b\x32\x18.YrcfAgent.BlockLinkInfo2\x84\x02\n\x07\x42lockIO\x12W\n\x0eListBlockLinks\x12 .YrcfAgent.ListBlockLinksRequest\x1a!.YrcfAgent.ListBlockLinksResponse0\x01\x12O\n\x0c\x41\x64\x64\x42lockLink\x12\x1e.YrcfAgent.AddBlockLinkRequest\x1a\x1f.YrcfAgent.AddBlockLinkResponse\x12O\n\x0c\x44\x65lBlockLink\x12\x1e.YrcfAgent.DelBlockLinkRequest\x1a\x1f.YrcfAgent.DelBlockLinkResponseb\x06proto3')



_BLOCKLINKINFO = DESCRIPTOR.message_types_by_name['BlockLinkInfo']
_ADDBLOCKLINKREQUEST = DESCRIPTOR.message_types_by_name['AddBlockLinkRequest']
_ADDBLOCKLINKRESPONSE = DESCRIPTOR.message_types_by_name['AddBlockLinkResponse']
_DELBLOCKLINKREQUEST = DESCRIPTOR.message_types_by_name['DelBlockLinkRequest']
_DELBLOCKLINKRESPONSE = DESCRIPTOR.message_types_by_name['DelBlockLinkResponse']
_LISTBLOCKLINKSREQUEST = DESCRIPTOR.message_types_by_name['ListBlockLinksRequest']
_LISTBLOCKLINKSRESPONSE = DESCRIPTOR.message_types_by_name['ListBlockLinksResponse']
_BLOCKLINKINFO_BLOCKTYPE = _BLOCKLINKINFO.enum_types_by_name['BlockType']
BlockLinkInfo = _reflection.GeneratedProtocolMessageType('BlockLinkInfo', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKLINKINFO,
  '__module__' : 'blockio_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.BlockLinkInfo)
  })
_sym_db.RegisterMessage(BlockLinkInfo)

AddBlockLinkRequest = _reflection.GeneratedProtocolMessageType('AddBlockLinkRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDBLOCKLINKREQUEST,
  '__module__' : 'blockio_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.AddBlockLinkRequest)
  })
_sym_db.RegisterMessage(AddBlockLinkRequest)

AddBlockLinkResponse = _reflection.GeneratedProtocolMessageType('AddBlockLinkResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDBLOCKLINKRESPONSE,
  '__module__' : 'blockio_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.AddBlockLinkResponse)
  })
_sym_db.RegisterMessage(AddBlockLinkResponse)

DelBlockLinkRequest = _reflection.GeneratedProtocolMessageType('DelBlockLinkRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELBLOCKLINKREQUEST,
  '__module__' : 'blockio_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.DelBlockLinkRequest)
  })
_sym_db.RegisterMessage(DelBlockLinkRequest)

DelBlockLinkResponse = _reflection.GeneratedProtocolMessageType('DelBlockLinkResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELBLOCKLINKRESPONSE,
  '__module__' : 'blockio_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.DelBlockLinkResponse)
  })
_sym_db.RegisterMessage(DelBlockLinkResponse)

ListBlockLinksRequest = _reflection.GeneratedProtocolMessageType('ListBlockLinksRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTBLOCKLINKSREQUEST,
  '__module__' : 'blockio_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.ListBlockLinksRequest)
  })
_sym_db.RegisterMessage(ListBlockLinksRequest)

ListBlockLinksResponse = _reflection.GeneratedProtocolMessageType('ListBlockLinksResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTBLOCKLINKSRESPONSE,
  '__module__' : 'blockio_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.ListBlockLinksResponse)
  })
_sym_db.RegisterMessage(ListBlockLinksResponse)

_BLOCKIO = DESCRIPTOR.services_by_name['BlockIO']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BLOCKLINKINFO._serialized_start=45
  _BLOCKLINKINFO._serialized_end=182
  _BLOCKLINKINFO_BLOCKTYPE._serialized_start=135
  _BLOCKLINKINFO_BLOCKTYPE._serialized_end=182
  _ADDBLOCKLINKREQUEST._serialized_start=184
  _ADDBLOCKLINKREQUEST._serialized_end=256
  _ADDBLOCKLINKRESPONSE._serialized_start=258
  _ADDBLOCKLINKRESPONSE._serialized_end=315
  _DELBLOCKLINKREQUEST._serialized_start=317
  _DELBLOCKLINKREQUEST._serialized_end=389
  _DELBLOCKLINKRESPONSE._serialized_start=391
  _DELBLOCKLINKRESPONSE._serialized_end=448
  _LISTBLOCKLINKSREQUEST._serialized_start=450
  _LISTBLOCKLINKSREQUEST._serialized_end=473
  _LISTBLOCKLINKSRESPONSE._serialized_start=475
  _LISTBLOCKLINKSRESPONSE._serialized_end=580
  _BLOCKIO._serialized_start=583
  _BLOCKIO._serialized_end=843
# @@protoc_insertion_point(module_scope)
