# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import bucket_pb2 as bucket__pb2


class BucketStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListBuckets = channel.unary_stream(
        '/YrcfAgent.Bucket/ListBuckets',
        request_serializer=bucket__pb2.ListBucketsRequest.SerializeToString,
        response_deserializer=bucket__pb2.ListBucketsResponse.FromString,
        )
    self.AddOrTestBucket = channel.unary_unary(
        '/YrcfAgent.Bucket/AddOrTestBucket',
        request_serializer=bucket__pb2.AddOrTestBucketRequest.SerializeToString,
        response_deserializer=bucket__pb2.AddOrTestBucketResponse.FromString,
        )
    self.UpdateBucket = channel.unary_unary(
        '/YrcfAgent.Bucket/UpdateBucket',
        request_serializer=bucket__pb2.UpdateBucketRequest.SerializeToString,
        response_deserializer=bucket__pb2.UpdateBucketResponse.FromString,
        )


class BucketServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListBuckets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddOrTestBucket(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateBucket(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BucketServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListBuckets': grpc.unary_stream_rpc_method_handler(
          servicer.ListBuckets,
          request_deserializer=bucket__pb2.ListBucketsRequest.FromString,
          response_serializer=bucket__pb2.ListBucketsResponse.SerializeToString,
      ),
      'AddOrTestBucket': grpc.unary_unary_rpc_method_handler(
          servicer.AddOrTestBucket,
          request_deserializer=bucket__pb2.AddOrTestBucketRequest.FromString,
          response_serializer=bucket__pb2.AddOrTestBucketResponse.SerializeToString,
      ),
      'UpdateBucket': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateBucket,
          request_deserializer=bucket__pb2.UpdateBucketRequest.FromString,
          response_serializer=bucket__pb2.UpdateBucketResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'YrcfAgent.Bucket', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
