# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import common.grpc.bucket_pb2 as bucket__pb2


class BucketStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListBuckets = channel.unary_stream(
                '/YrcfAgent.Bucket/ListBuckets',
                request_serializer=bucket__pb2.ListBucketsRequest.SerializeToString,
                response_deserializer=bucket__pb2.ListBucketsResponse.FromString,
                )
        self.AddOrTestBucket = channel.unary_unary(
                '/YrcfAgent.Bucket/AddOrTestBucket',
                request_serializer=bucket__pb2.AddOrTestBucketRequest.SerializeToString,
                response_deserializer=bucket__pb2.AddOrTestBucketResponse.FromString,
                )
        self.UpdateBucket = channel.unary_unary(
                '/YrcfAgent.Bucket/UpdateBucket',
                request_serializer=bucket__pb2.UpdateBucketRequest.SerializeToString,
                response_deserializer=bucket__pb2.UpdateBucketResponse.FromString,
                )


class BucketServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListBuckets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddOrTestBucket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBucket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BucketServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListBuckets': grpc.unary_stream_rpc_method_handler(
                    servicer.ListBuckets,
                    request_deserializer=bucket__pb2.ListBucketsRequest.FromString,
                    response_serializer=bucket__pb2.ListBucketsResponse.SerializeToString,
            ),
            'AddOrTestBucket': grpc.unary_unary_rpc_method_handler(
                    servicer.AddOrTestBucket,
                    request_deserializer=bucket__pb2.AddOrTestBucketRequest.FromString,
                    response_serializer=bucket__pb2.AddOrTestBucketResponse.SerializeToString,
            ),
            'UpdateBucket': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBucket,
                    request_deserializer=bucket__pb2.UpdateBucketRequest.FromString,
                    response_serializer=bucket__pb2.UpdateBucketResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'YrcfAgent.Bucket', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Bucket(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListBuckets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/YrcfAgent.Bucket/ListBuckets',
            bucket__pb2.ListBucketsRequest.SerializeToString,
            bucket__pb2.ListBucketsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddOrTestBucket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/YrcfAgent.Bucket/AddOrTestBucket',
            bucket__pb2.AddOrTestBucketRequest.SerializeToString,
            bucket__pb2.AddOrTestBucketResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateBucket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/YrcfAgent.Bucket/UpdateBucket',
            bucket__pb2.UpdateBucketRequest.SerializeToString,
            bucket__pb2.UpdateBucketResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
