# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import clientstats_pb2 as clientstats__pb2


class ClientStatsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MdsStats = channel.unary_unary(
                '/YrcfAgent.ClientStats/MdsStats',
                request_serializer=clientstats__pb2.ClientStatsPara.SerializeToString,
                response_deserializer=clientstats__pb2.ClientStatsResponse.FromString,
                )
        self.OssStats = channel.unary_unary(
                '/YrcfAgent.ClientStats/OssStats',
                request_serializer=clientstats__pb2.ClientStatsPara.SerializeToString,
                response_deserializer=clientstats__pb2.ClientStatsResponse.FromString,
                )


class ClientStatsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MdsStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OssStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientStatsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MdsStats': grpc.unary_unary_rpc_method_handler(
                    servicer.MdsStats,
                    request_deserializer=clientstats__pb2.ClientStatsPara.FromString,
                    response_serializer=clientstats__pb2.ClientStatsResponse.SerializeToString,
            ),
            'OssStats': grpc.unary_unary_rpc_method_handler(
                    servicer.OssStats,
                    request_deserializer=clientstats__pb2.ClientStatsPara.FromString,
                    response_serializer=clientstats__pb2.ClientStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'YrcfAgent.ClientStats', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClientStats(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MdsStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/YrcfAgent.ClientStats/MdsStats',
            clientstats__pb2.ClientStatsPara.SerializeToString,
            clientstats__pb2.ClientStatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OssStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/YrcfAgent.ClientStats/OssStats',
            clientstats__pb2.ClientStatsPara.SerializeToString,
            clientstats__pb2.ClientStatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
