# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clientstats.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63lientstats.proto\x12\tYrcfAgent\x1a\x0eresponse.proto\"b\n\x0f\x43lientStatsPara\x12\x19\n\x11hide_internal_ips\x18\x02 \x01(\x08\x12\x19\n\x11return_zero_stats\x18\x03 \x01(\x08\x12\x19\n\x11\x63lient_stats_type\x18\x04 \x01(\r\"@\n\x0e\x43lientStatsRet\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0e\n\x06online\x18\x02 \x01(\x08\x12\x12\n\nopcounters\x18\x03 \x03(\x04\"b\n\x13\x43lientStatsResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.YrcfAgent.ClientStatsRet2\xa1\x01\n\x0b\x43lientStats\x12H\n\x08MdsStats\x12\x1a.YrcfAgent.ClientStatsPara\x1a\x1e.YrcfAgent.ClientStatsResponse\"\x00\x12H\n\x08OssStats\x12\x1a.YrcfAgent.ClientStatsPara\x1a\x1e.YrcfAgent.ClientStatsResponse\"\x00\x62\x06proto3')



_CLIENTSTATSPARA = DESCRIPTOR.message_types_by_name['ClientStatsPara']
_CLIENTSTATSRET = DESCRIPTOR.message_types_by_name['ClientStatsRet']
_CLIENTSTATSRESPONSE = DESCRIPTOR.message_types_by_name['ClientStatsResponse']
ClientStatsPara = _reflection.GeneratedProtocolMessageType('ClientStatsPara', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTSTATSPARA,
  '__module__' : 'clientstats_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.ClientStatsPara)
  })
_sym_db.RegisterMessage(ClientStatsPara)

ClientStatsRet = _reflection.GeneratedProtocolMessageType('ClientStatsRet', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTSTATSRET,
  '__module__' : 'clientstats_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.ClientStatsRet)
  })
_sym_db.RegisterMessage(ClientStatsRet)

ClientStatsResponse = _reflection.GeneratedProtocolMessageType('ClientStatsResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTSTATSRESPONSE,
  '__module__' : 'clientstats_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.ClientStatsResponse)
  })
_sym_db.RegisterMessage(ClientStatsResponse)

_CLIENTSTATS = DESCRIPTOR.services_by_name['ClientStats']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTSTATSPARA._serialized_start=48
  _CLIENTSTATSPARA._serialized_end=146
  _CLIENTSTATSRET._serialized_start=148
  _CLIENTSTATSRET._serialized_end=212
  _CLIENTSTATSRESPONSE._serialized_start=214
  _CLIENTSTATSRESPONSE._serialized_end=312
  _CLIENTSTATS._serialized_start=315
  _CLIENTSTATS._serialized_end=476
# @@protoc_insertion_point(module_scope)
