# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clientstats.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='clientstats.proto',
  package='YrcfAgent',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x63lientstats.proto\x12\tYrcfAgent\x1a\x0eresponse.proto\"b\n\x0f\x43lientStatsPara\x12\x19\n\x11hide_internal_ips\x18\x02 \x01(\x08\x12\x19\n\x11return_zero_stats\x18\x03 \x01(\x08\x12\x19\n\x11\x63lient_stats_type\x18\x04 \x01(\r\"@\n\x0e\x43lientStatsRet\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0e\n\x06online\x18\x02 \x01(\x08\x12\x12\n\nopcounters\x18\x03 \x03(\x04\"b\n\x13\x43lientStatsResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.YrcfAgent.ClientStatsRet2\xa1\x01\n\x0b\x43lientStats\x12H\n\x08MdsStats\x12\x1a.YrcfAgent.ClientStatsPara\x1a\x1e.YrcfAgent.ClientStatsResponse\"\x00\x12H\n\x08OssStats\x12\x1a.YrcfAgent.ClientStatsPara\x1a\x1e.YrcfAgent.ClientStatsResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[response__pb2.DESCRIPTOR,])




_CLIENTSTATSPARA = _descriptor.Descriptor(
  name='ClientStatsPara',
  full_name='YrcfAgent.ClientStatsPara',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hide_internal_ips', full_name='YrcfAgent.ClientStatsPara.hide_internal_ips', index=0,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='return_zero_stats', full_name='YrcfAgent.ClientStatsPara.return_zero_stats', index=1,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_stats_type', full_name='YrcfAgent.ClientStatsPara.client_stats_type', index=2,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=146,
)


_CLIENTSTATSRET = _descriptor.Descriptor(
  name='ClientStatsRet',
  full_name='YrcfAgent.ClientStatsRet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='YrcfAgent.ClientStatsRet.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='online', full_name='YrcfAgent.ClientStatsRet.online', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='opcounters', full_name='YrcfAgent.ClientStatsRet.opcounters', index=2,
      number=3, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=212,
)


_CLIENTSTATSRESPONSE = _descriptor.Descriptor(
  name='ClientStatsResponse',
  full_name='YrcfAgent.ClientStatsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='YrcfAgent.ClientStatsResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='YrcfAgent.ClientStatsResponse.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=312,
)

_CLIENTSTATSRESPONSE.fields_by_name['result'].message_type = response__pb2._RESMES
_CLIENTSTATSRESPONSE.fields_by_name['value'].message_type = _CLIENTSTATSRET
DESCRIPTOR.message_types_by_name['ClientStatsPara'] = _CLIENTSTATSPARA
DESCRIPTOR.message_types_by_name['ClientStatsRet'] = _CLIENTSTATSRET
DESCRIPTOR.message_types_by_name['ClientStatsResponse'] = _CLIENTSTATSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientStatsPara = _reflection.GeneratedProtocolMessageType('ClientStatsPara', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTSTATSPARA,
  __module__ = 'clientstats_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.ClientStatsPara)
  ))
_sym_db.RegisterMessage(ClientStatsPara)

ClientStatsRet = _reflection.GeneratedProtocolMessageType('ClientStatsRet', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTSTATSRET,
  __module__ = 'clientstats_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.ClientStatsRet)
  ))
_sym_db.RegisterMessage(ClientStatsRet)

ClientStatsResponse = _reflection.GeneratedProtocolMessageType('ClientStatsResponse', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTSTATSRESPONSE,
  __module__ = 'clientstats_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.ClientStatsResponse)
  ))
_sym_db.RegisterMessage(ClientStatsResponse)



_CLIENTSTATS = _descriptor.ServiceDescriptor(
  name='ClientStats',
  full_name='YrcfAgent.ClientStats',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=315,
  serialized_end=476,
  methods=[
  _descriptor.MethodDescriptor(
    name='MdsStats',
    full_name='YrcfAgent.ClientStats.MdsStats',
    index=0,
    containing_service=None,
    input_type=_CLIENTSTATSPARA,
    output_type=_CLIENTSTATSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='OssStats',
    full_name='YrcfAgent.ClientStats.OssStats',
    index=1,
    containing_service=None,
    input_type=_CLIENTSTATSPARA,
    output_type=_CLIENTSTATSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLIENTSTATS)

DESCRIPTOR.services_by_name['ClientStats'] = _CLIENTSTATS

# @@protoc_insertion_point(module_scope)
