# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dumpinode.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dumpinode.proto',
  package='YrcfAgent',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x64umpinode.proto\x12\tYrcfAgent\x1a\x0eresponse.proto\"\xcd\x01\n\x10\x44umpInodeRequest\x12\x19\n\x11use_absolute_path\x18\x01 \x01(\x08\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x32\n\x04type\x18\x03 \x01(\x0e\x32$.YrcfAgent.DumpInodeRequest.NodeType\x12\x10\n\x08\x65ntry_id\x18\x04 \x01(\t\x12\x12\n\nowner_only\x18\x05 \x01(\x08\x12\x0f\n\x07node_id\x18\x06 \x01(\t\"%\n\x08NodeType\x12\x07\n\x03MGR\x10\x00\x12\x07\n\x03MDS\x10\x01\x12\x07\n\x03OSS\x10\x02\"q\n\x11\x44umpInodeResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x15\n\rresponse_from\x18\x03 \x01(\t\x12\x11\n\tresp_info\x18\x04 \x01(\t2U\n\tDumpInode\x12H\n\tDumpInode\x12\x1b.YrcfAgent.DumpInodeRequest\x1a\x1c.YrcfAgent.DumpInodeResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[response__pb2.DESCRIPTOR,])



_DUMPINODEREQUEST_NODETYPE = _descriptor.EnumDescriptor(
  name='NodeType',
  full_name='YrcfAgent.DumpInodeRequest.NodeType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MGR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MDS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OSS', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=215,
  serialized_end=252,
)
_sym_db.RegisterEnumDescriptor(_DUMPINODEREQUEST_NODETYPE)


_DUMPINODEREQUEST = _descriptor.Descriptor(
  name='DumpInodeRequest',
  full_name='YrcfAgent.DumpInodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='use_absolute_path', full_name='YrcfAgent.DumpInodeRequest.use_absolute_path', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='YrcfAgent.DumpInodeRequest.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='YrcfAgent.DumpInodeRequest.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entry_id', full_name='YrcfAgent.DumpInodeRequest.entry_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner_only', full_name='YrcfAgent.DumpInodeRequest.owner_only', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node_id', full_name='YrcfAgent.DumpInodeRequest.node_id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DUMPINODEREQUEST_NODETYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=252,
)


_DUMPINODERESPONSE = _descriptor.Descriptor(
  name='DumpInodeResponse',
  full_name='YrcfAgent.DumpInodeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='YrcfAgent.DumpInodeResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command', full_name='YrcfAgent.DumpInodeResponse.command', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response_from', full_name='YrcfAgent.DumpInodeResponse.response_from', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resp_info', full_name='YrcfAgent.DumpInodeResponse.resp_info', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=367,
)

_DUMPINODEREQUEST.fields_by_name['type'].enum_type = _DUMPINODEREQUEST_NODETYPE
_DUMPINODEREQUEST_NODETYPE.containing_type = _DUMPINODEREQUEST
_DUMPINODERESPONSE.fields_by_name['result'].message_type = response__pb2._RESMES
DESCRIPTOR.message_types_by_name['DumpInodeRequest'] = _DUMPINODEREQUEST
DESCRIPTOR.message_types_by_name['DumpInodeResponse'] = _DUMPINODERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DumpInodeRequest = _reflection.GeneratedProtocolMessageType('DumpInodeRequest', (_message.Message,), dict(
  DESCRIPTOR = _DUMPINODEREQUEST,
  __module__ = 'dumpinode_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.DumpInodeRequest)
  ))
_sym_db.RegisterMessage(DumpInodeRequest)

DumpInodeResponse = _reflection.GeneratedProtocolMessageType('DumpInodeResponse', (_message.Message,), dict(
  DESCRIPTOR = _DUMPINODERESPONSE,
  __module__ = 'dumpinode_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.DumpInodeResponse)
  ))
_sym_db.RegisterMessage(DumpInodeResponse)



_DUMPINODE = _descriptor.ServiceDescriptor(
  name='DumpInode',
  full_name='YrcfAgent.DumpInode',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=369,
  serialized_end=454,
  methods=[
  _descriptor.MethodDescriptor(
    name='DumpInode',
    full_name='YrcfAgent.DumpInode.DumpInode',
    index=0,
    containing_service=None,
    input_type=_DUMPINODEREQUEST,
    output_type=_DUMPINODERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DUMPINODE)

DESCRIPTOR.services_by_name['DumpInode'] = _DUMPINODE

# @@protoc_insertion_point(module_scope)
