# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dumpinode.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64umpinode.proto\x12\tYrcfAgent\x1a\x0eresponse.proto\"\xcd\x01\n\x10\x44umpInodeRequest\x12\x19\n\x11use_absolute_path\x18\x01 \x01(\x08\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x32\n\x04type\x18\x03 \x01(\x0e\x32$.YrcfAgent.DumpInodeRequest.NodeType\x12\x10\n\x08\x65ntry_id\x18\x04 \x01(\t\x12\x12\n\nowner_only\x18\x05 \x01(\x08\x12\x0f\n\x07node_id\x18\x06 \x01(\t\"%\n\x08NodeType\x12\x07\n\x03MGR\x10\x00\x12\x07\n\x03MDS\x10\x01\x12\x07\n\x03OSS\x10\x02\"q\n\x11\x44umpInodeResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x15\n\rresponse_from\x18\x03 \x01(\t\x12\x11\n\tresp_info\x18\x04 \x01(\t2U\n\tDumpInode\x12H\n\tDumpInode\x12\x1b.YrcfAgent.DumpInodeRequest\x1a\x1c.YrcfAgent.DumpInodeResponse\"\x00\x62\x06proto3')



_DUMPINODEREQUEST = DESCRIPTOR.message_types_by_name['DumpInodeRequest']
_DUMPINODERESPONSE = DESCRIPTOR.message_types_by_name['DumpInodeResponse']
_DUMPINODEREQUEST_NODETYPE = _DUMPINODEREQUEST.enum_types_by_name['NodeType']
DumpInodeRequest = _reflection.GeneratedProtocolMessageType('DumpInodeRequest', (_message.Message,), {
  'DESCRIPTOR' : _DUMPINODEREQUEST,
  '__module__' : 'dumpinode_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.DumpInodeRequest)
  })
_sym_db.RegisterMessage(DumpInodeRequest)

DumpInodeResponse = _reflection.GeneratedProtocolMessageType('DumpInodeResponse', (_message.Message,), {
  'DESCRIPTOR' : _DUMPINODERESPONSE,
  '__module__' : 'dumpinode_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.DumpInodeResponse)
  })
_sym_db.RegisterMessage(DumpInodeResponse)

_DUMPINODE = DESCRIPTOR.services_by_name['DumpInode']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DUMPINODEREQUEST._serialized_start=47
  _DUMPINODEREQUEST._serialized_end=252
  _DUMPINODEREQUEST_NODETYPE._serialized_start=215
  _DUMPINODEREQUEST_NODETYPE._serialized_end=252
  _DUMPINODERESPONSE._serialized_start=254
  _DUMPINODERESPONSE._serialized_end=367
  _DUMPINODE._serialized_start=369
  _DUMPINODE._serialized_end=454
# @@protoc_insertion_point(module_scope)
