# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import getentry_pb2 as getentry__pb2


class GetEntryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEntry = channel.unary_unary(
                '/YrcfAgent.GetEntry/GetEntry',
                request_serializer=getentry__pb2.GetEntryRequest.SerializeToString,
                response_deserializer=getentry__pb2.GetEntryResponse.FromString,
                )


class GetEntryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetEntryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntry,
                    request_deserializer=getentry__pb2.GetEntryRequest.FromString,
                    response_serializer=getentry__pb2.GetEntryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'YrcfAgent.GetEntry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GetEntry(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/YrcfAgent.GetEntry/GetEntry',
            getentry__pb2.GetEntryRequest.SerializeToString,
            getentry__pb2.GetEntryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
