# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: getentry.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egetentry.proto\x12\tYrcfAgent\x1a\x0eresponse.proto\"\\\n\x08MetaInfo\x12\x0b\n\x03\x65id\x18\x01 \x01(\t\x12\x0c\n\x04peid\x18\x02 \x01(\t\x12\x12\n\nredundancy\x18\x03 \x01(\t\x12\x10\n\x08group_id\x18\x04 \x01(\t\x12\x0f\n\x07node_id\x18\x05 \x01(\t\"\xb3\x01\n\x08\x44\x61taInfo\x12\x15\n\rdata_location\x18\x01 \x01(\t\x12\x12\n\nredundancy\x18\x02 \x01(\t\x12\x12\n\ntiering_id\x18\x03 \x01(\r\x12\x16\n\x0e\x62ucket_link_id\x18\x04 \x01(\r\x12\x12\n\nproject_id\x18\x05 \x01(\r\x12\x13\n\x0bstripe_size\x18\x06 \x01(\t\x12\x14\n\x0cstripe_count\x18\x07 \x01(\t\x12\x11\n\tplacement\x18\x08 \x01(\t\":\n\x0fGetEntryRequest\x12\x19\n\x11use_absolute_path\x18\x01 \x01(\x08\x12\x0c\n\x04path\x18\x02 \x01(\t\"\x85\x01\n\x10GetEntryResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes\x12&\n\tmeta_info\x18\x02 \x01(\x0b\x32\x13.YrcfAgent.MetaInfo\x12&\n\tdata_info\x18\x03 \x01(\x0b\x32\x13.YrcfAgent.DataInfo2Q\n\x08GetEntry\x12\x45\n\x08GetEntry\x12\x1a.YrcfAgent.GetEntryRequest\x1a\x1b.YrcfAgent.GetEntryResponse\"\x00\x62\x06proto3')



_METAINFO = DESCRIPTOR.message_types_by_name['MetaInfo']
_DATAINFO = DESCRIPTOR.message_types_by_name['DataInfo']
_GETENTRYREQUEST = DESCRIPTOR.message_types_by_name['GetEntryRequest']
_GETENTRYRESPONSE = DESCRIPTOR.message_types_by_name['GetEntryResponse']
MetaInfo = _reflection.GeneratedProtocolMessageType('MetaInfo', (_message.Message,), {
  'DESCRIPTOR' : _METAINFO,
  '__module__' : 'getentry_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.MetaInfo)
  })
_sym_db.RegisterMessage(MetaInfo)

DataInfo = _reflection.GeneratedProtocolMessageType('DataInfo', (_message.Message,), {
  'DESCRIPTOR' : _DATAINFO,
  '__module__' : 'getentry_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.DataInfo)
  })
_sym_db.RegisterMessage(DataInfo)

GetEntryRequest = _reflection.GeneratedProtocolMessageType('GetEntryRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETENTRYREQUEST,
  '__module__' : 'getentry_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.GetEntryRequest)
  })
_sym_db.RegisterMessage(GetEntryRequest)

GetEntryResponse = _reflection.GeneratedProtocolMessageType('GetEntryResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETENTRYRESPONSE,
  '__module__' : 'getentry_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.GetEntryResponse)
  })
_sym_db.RegisterMessage(GetEntryResponse)

_GETENTRY = DESCRIPTOR.services_by_name['GetEntry']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _METAINFO._serialized_start=45
  _METAINFO._serialized_end=137
  _DATAINFO._serialized_start=140
  _DATAINFO._serialized_end=319
  _GETENTRYREQUEST._serialized_start=321
  _GETENTRYREQUEST._serialized_end=379
  _GETENTRYRESPONSE._serialized_start=382
  _GETENTRYRESPONSE._serialized_end=515
  _GETENTRY._serialized_start=517
  _GETENTRY._serialized_end=598
# @@protoc_insertion_point(module_scope)
