# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: getsla.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgetsla.proto\x12\tYrcfAgent\x1a\x0eresponse.proto\"\xa8\x01\n\x07SlaInfo\x12\x15\n\rread_times_ps\x18\x01 \x01(\x04\x12\x16\n\x0ewrite_times_ps\x18\x02 \x01(\x04\x12\x16\n\x0etotal_times_ps\x18\x03 \x01(\x04\x12\x15\n\rread_bytes_ps\x18\x04 \x01(\x04\x12\x16\n\x0ewrite_bytes_ps\x18\x05 \x01(\x04\x12\x16\n\x0etotal_bytes_ps\x18\x06 \x01(\x04\x12\x0f\n\x07mds_ops\x18\x07 \x01(\x04\"8\n\rGetSlaRequest\x12\x19\n\x11use_absolute_path\x18\x01 \x01(\x08\x12\x0c\n\x04path\x18\x02 \x01(\t\"{\n\x0eGetSlaResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x12\n\nentry_info\x18\x03 \x01(\t\x12$\n\x08sla_info\x18\x04 \x03(\x0b\x32\x12.YrcfAgent.SlaInfo2I\n\x06GetSla\x12?\n\x06GetSla\x12\x18.YrcfAgent.GetSlaRequest\x1a\x19.YrcfAgent.GetSlaResponse\"\x00\x62\x06proto3')



_SLAINFO = DESCRIPTOR.message_types_by_name['SlaInfo']
_GETSLAREQUEST = DESCRIPTOR.message_types_by_name['GetSlaRequest']
_GETSLARESPONSE = DESCRIPTOR.message_types_by_name['GetSlaResponse']
SlaInfo = _reflection.GeneratedProtocolMessageType('SlaInfo', (_message.Message,), {
  'DESCRIPTOR' : _SLAINFO,
  '__module__' : 'getsla_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.SlaInfo)
  })
_sym_db.RegisterMessage(SlaInfo)

GetSlaRequest = _reflection.GeneratedProtocolMessageType('GetSlaRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSLAREQUEST,
  '__module__' : 'getsla_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.GetSlaRequest)
  })
_sym_db.RegisterMessage(GetSlaRequest)

GetSlaResponse = _reflection.GeneratedProtocolMessageType('GetSlaResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSLARESPONSE,
  '__module__' : 'getsla_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.GetSlaResponse)
  })
_sym_db.RegisterMessage(GetSlaResponse)

_GETSLA = DESCRIPTOR.services_by_name['GetSla']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SLAINFO._serialized_start=44
  _SLAINFO._serialized_end=212
  _GETSLAREQUEST._serialized_start=214
  _GETSLAREQUEST._serialized_end=270
  _GETSLARESPONSE._serialized_start=272
  _GETSLARESPONSE._serialized_end=395
  _GETSLA._serialized_start=397
  _GETSLA._serialized_end=470
# @@protoc_insertion_point(module_scope)
