# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import getsla_pb2 as getsla__pb2


class GetSlaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSla = channel.unary_unary(
                '/YrcfAgent.GetSla/GetSla',
                request_serializer=getsla__pb2.GetSlaRequest.SerializeToString,
                response_deserializer=getsla__pb2.GetSlaResponse.FromString,
                )


class GetSlaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSla(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetSlaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSla': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSla,
                    request_deserializer=getsla__pb2.GetSlaRequest.FromString,
                    response_serializer=getsla__pb2.GetSlaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'YrcfAgent.GetSla', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GetSla(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSla(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/YrcfAgent.GetSla/GetSla',
            getsla__pb2.GetSlaRequest.SerializeToString,
            getsla__pb2.GetSlaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
