# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import getsla_pb2 as getsla__pb2


class GetSlaStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSla = channel.unary_unary(
        '/YrcfAgent.GetSla/GetSla',
        request_serializer=getsla__pb2.GetSlaRequest.SerializeToString,
        response_deserializer=getsla__pb2.GetSlaResponse.FromString,
        )


class GetSlaServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetSla(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GetSlaServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSla': grpc.unary_unary_rpc_method_handler(
          servicer.GetSla,
          request_deserializer=getsla__pb2.GetSlaRequest.FromString,
          response_serializer=getsla__pb2.GetSlaResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'YrcfAgent.GetSla', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
