# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: getsla.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='getsla.proto',
  package='YrcfAgent',
  syntax='proto3',
  serialized_pb=_b('\n\x0cgetsla.proto\x12\tYrcfAgent\x1a\x0eresponse.proto\"\xa8\x01\n\x07SlaInfo\x12\x15\n\rread_times_ps\x18\x01 \x01(\x04\x12\x16\n\x0ewrite_times_ps\x18\x02 \x01(\x04\x12\x16\n\x0etotal_times_ps\x18\x03 \x01(\x04\x12\x15\n\rread_bytes_ps\x18\x04 \x01(\x04\x12\x16\n\x0ewrite_bytes_ps\x18\x05 \x01(\x04\x12\x16\n\x0etotal_bytes_ps\x18\x06 \x01(\x04\x12\x0f\n\x07mds_ops\x18\x07 \x01(\x04\"8\n\rGetSlaRequest\x12\x19\n\x11use_absolute_path\x18\x01 \x01(\x08\x12\x0c\n\x04path\x18\x02 \x01(\t\"{\n\x0eGetSlaResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x12\n\nentry_info\x18\x03 \x01(\t\x12$\n\x08sla_info\x18\x04 \x03(\x0b\x32\x12.YrcfAgent.SlaInfo2I\n\x06GetSla\x12?\n\x06GetSla\x12\x18.YrcfAgent.GetSlaRequest\x1a\x19.YrcfAgent.GetSlaResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[response__pb2.DESCRIPTOR,])




_SLAINFO = _descriptor.Descriptor(
  name='SlaInfo',
  full_name='YrcfAgent.SlaInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='read_times_ps', full_name='YrcfAgent.SlaInfo.read_times_ps', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='write_times_ps', full_name='YrcfAgent.SlaInfo.write_times_ps', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_times_ps', full_name='YrcfAgent.SlaInfo.total_times_ps', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='read_bytes_ps', full_name='YrcfAgent.SlaInfo.read_bytes_ps', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='write_bytes_ps', full_name='YrcfAgent.SlaInfo.write_bytes_ps', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_bytes_ps', full_name='YrcfAgent.SlaInfo.total_bytes_ps', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mds_ops', full_name='YrcfAgent.SlaInfo.mds_ops', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=212,
)


_GETSLAREQUEST = _descriptor.Descriptor(
  name='GetSlaRequest',
  full_name='YrcfAgent.GetSlaRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='use_absolute_path', full_name='YrcfAgent.GetSlaRequest.use_absolute_path', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='YrcfAgent.GetSlaRequest.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=270,
)


_GETSLARESPONSE = _descriptor.Descriptor(
  name='GetSlaResponse',
  full_name='YrcfAgent.GetSlaResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='YrcfAgent.GetSlaResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='YrcfAgent.GetSlaResponse.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entry_info', full_name='YrcfAgent.GetSlaResponse.entry_info', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sla_info', full_name='YrcfAgent.GetSlaResponse.sla_info', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=395,
)

_GETSLARESPONSE.fields_by_name['result'].message_type = response__pb2._RESMES
_GETSLARESPONSE.fields_by_name['sla_info'].message_type = _SLAINFO
DESCRIPTOR.message_types_by_name['SlaInfo'] = _SLAINFO
DESCRIPTOR.message_types_by_name['GetSlaRequest'] = _GETSLAREQUEST
DESCRIPTOR.message_types_by_name['GetSlaResponse'] = _GETSLARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SlaInfo = _reflection.GeneratedProtocolMessageType('SlaInfo', (_message.Message,), dict(
  DESCRIPTOR = _SLAINFO,
  __module__ = 'getsla_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.SlaInfo)
  ))
_sym_db.RegisterMessage(SlaInfo)

GetSlaRequest = _reflection.GeneratedProtocolMessageType('GetSlaRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETSLAREQUEST,
  __module__ = 'getsla_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.GetSlaRequest)
  ))
_sym_db.RegisterMessage(GetSlaRequest)

GetSlaResponse = _reflection.GeneratedProtocolMessageType('GetSlaResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETSLARESPONSE,
  __module__ = 'getsla_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.GetSlaResponse)
  ))
_sym_db.RegisterMessage(GetSlaResponse)



_GETSLA = _descriptor.ServiceDescriptor(
  name='GetSla',
  full_name='YrcfAgent.GetSla',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=397,
  serialized_end=470,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSla',
    full_name='YrcfAgent.GetSla.GetSla',
    index=0,
    containing_service=None,
    input_type=_GETSLAREQUEST,
    output_type=_GETSLARESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GETSLA)

DESCRIPTOR.services_by_name['GetSla'] = _GETSLA

# @@protoc_insertion_point(module_scope)
