# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlicense.proto\x12\tYrcfAgent\x1a\x0eresponse.proto\"\x10\n\x0eGetLicensePara\"\x1d\n\rGetLicenseRet\x12\x0c\n\x04time\x18\x01 \x01(\t\"`\n\x12GetLicenseResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.YrcfAgent.GetLicenseRet\"\x1e\n\x0eSetLicensePara\x12\x0c\n\x04path\x18\x01 \x01(\t\"7\n\x12SetLicenseResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes\"\x14\n\x12RequestLicensePara\";\n\x16RequestLicenseResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes2\xf3\x01\n\x07License\x12H\n\nGetLicense\x12\x19.YrcfAgent.GetLicensePara\x1a\x1d.YrcfAgent.GetLicenseResponse\"\x00\x12H\n\nSetLicense\x12\x19.YrcfAgent.SetLicensePara\x1a\x1d.YrcfAgent.SetLicenseResponse\"\x00\x12T\n\x0eRequestLicense\x12\x1d.YrcfAgent.RequestLicensePara\x1a!.YrcfAgent.RequestLicenseResponse\"\x00\x62\x06proto3')



_GETLICENSEPARA = DESCRIPTOR.message_types_by_name['GetLicensePara']
_GETLICENSERET = DESCRIPTOR.message_types_by_name['GetLicenseRet']
_GETLICENSERESPONSE = DESCRIPTOR.message_types_by_name['GetLicenseResponse']
_SETLICENSEPARA = DESCRIPTOR.message_types_by_name['SetLicensePara']
_SETLICENSERESPONSE = DESCRIPTOR.message_types_by_name['SetLicenseResponse']
_REQUESTLICENSEPARA = DESCRIPTOR.message_types_by_name['RequestLicensePara']
_REQUESTLICENSERESPONSE = DESCRIPTOR.message_types_by_name['RequestLicenseResponse']
GetLicensePara = _reflection.GeneratedProtocolMessageType('GetLicensePara', (_message.Message,), {
  'DESCRIPTOR' : _GETLICENSEPARA,
  '__module__' : 'license_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.GetLicensePara)
  })
_sym_db.RegisterMessage(GetLicensePara)

GetLicenseRet = _reflection.GeneratedProtocolMessageType('GetLicenseRet', (_message.Message,), {
  'DESCRIPTOR' : _GETLICENSERET,
  '__module__' : 'license_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.GetLicenseRet)
  })
_sym_db.RegisterMessage(GetLicenseRet)

GetLicenseResponse = _reflection.GeneratedProtocolMessageType('GetLicenseResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETLICENSERESPONSE,
  '__module__' : 'license_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.GetLicenseResponse)
  })
_sym_db.RegisterMessage(GetLicenseResponse)

SetLicensePara = _reflection.GeneratedProtocolMessageType('SetLicensePara', (_message.Message,), {
  'DESCRIPTOR' : _SETLICENSEPARA,
  '__module__' : 'license_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.SetLicensePara)
  })
_sym_db.RegisterMessage(SetLicensePara)

SetLicenseResponse = _reflection.GeneratedProtocolMessageType('SetLicenseResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETLICENSERESPONSE,
  '__module__' : 'license_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.SetLicenseResponse)
  })
_sym_db.RegisterMessage(SetLicenseResponse)

RequestLicensePara = _reflection.GeneratedProtocolMessageType('RequestLicensePara', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTLICENSEPARA,
  '__module__' : 'license_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.RequestLicensePara)
  })
_sym_db.RegisterMessage(RequestLicensePara)

RequestLicenseResponse = _reflection.GeneratedProtocolMessageType('RequestLicenseResponse', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTLICENSERESPONSE,
  '__module__' : 'license_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.RequestLicenseResponse)
  })
_sym_db.RegisterMessage(RequestLicenseResponse)

_LICENSE = DESCRIPTOR.services_by_name['License']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETLICENSEPARA._serialized_start=44
  _GETLICENSEPARA._serialized_end=60
  _GETLICENSERET._serialized_start=62
  _GETLICENSERET._serialized_end=91
  _GETLICENSERESPONSE._serialized_start=93
  _GETLICENSERESPONSE._serialized_end=189
  _SETLICENSEPARA._serialized_start=191
  _SETLICENSEPARA._serialized_end=221
  _SETLICENSERESPONSE._serialized_start=223
  _SETLICENSERESPONSE._serialized_end=278
  _REQUESTLICENSEPARA._serialized_start=280
  _REQUESTLICENSEPARA._serialized_end=300
  _REQUESTLICENSERESPONSE._serialized_start=302
  _REQUESTLICENSERESPONSE._serialized_end=361
  _LICENSE._serialized_start=364
  _LICENSE._serialized_end=607
# @@protoc_insertion_point(module_scope)
