# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import listosds_pb2 as listosds__pb2


class ListOsdsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListOsds = channel.unary_unary(
        '/YrcfAgent.ListOsds/ListOsds',
        request_serializer=listosds__pb2.ListOsdsRequest.SerializeToString,
        response_deserializer=listosds__pb2.ListOsdsResponse.FromString,
        )


class ListOsdsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListOsds(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ListOsdsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListOsds': grpc.unary_unary_rpc_method_handler(
          servicer.ListOsds,
          request_deserializer=listosds__pb2.ListOsdsRequest.FromString,
          response_serializer=listosds__pb2.ListOsdsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'YrcfAgent.ListOsds', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
