# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: listosds.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='listosds.proto',
  package='YrcfAgent',
  syntax='proto3',
  serialized_pb=_b('\n\x0elistosds.proto\x12\tYrcfAgent\x1a\x0eresponse.proto\"\xfc\x01\n\x07OsdInfo\x12,\n\x08osd_type\x18\x01 \x01(\x0e\x32\x1a.YrcfAgent.OsdInfo.OsdType\x12\x0e\n\x06osd_id\x18\x02 \x01(\r\x12\x11\n\tnode_name\x18\x03 \x01(\t\x12\x0f\n\x07node_id\x18\x04 \x01(\t\x12\x12\n\ngroup_info\x18\x05 \x01(\t\x12\x11\n\trole_info\x18\x06 \x01(\t\x12\x11\n\tstate_str\x18\x07 \x01(\t\x12\x11\n\tpool_name\x18\x08 \x01(\t\x12\x12\n\nspace_info\x18\t \x01(\t\x12\x11\n\tpool_info\x18\n \x01(\t\"\x1b\n\x07OsdType\x12\x07\n\x03OSS\x10\x00\x12\x07\n\x03MDS\x10\x01\"P\n\x0fListOsdsRequest\x12,\n\x08osd_type\x18\x01 \x01(\x0e\x32\x1a.YrcfAgent.OsdInfo.OsdType\x12\x0f\n\x07pool_id\x18\x02 \x01(\t\"`\n\x10ListOsdsResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes\x12)\n\rosd_info_list\x18\x02 \x03(\x0b\x32\x12.YrcfAgent.OsdInfo2Q\n\x08ListOsds\x12\x45\n\x08ListOsds\x12\x1a.YrcfAgent.ListOsdsRequest\x1a\x1b.YrcfAgent.ListOsdsResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[response__pb2.DESCRIPTOR,])



_OSDINFO_OSDTYPE = _descriptor.EnumDescriptor(
  name='OsdType',
  full_name='YrcfAgent.OsdInfo.OsdType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OSS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MDS', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=271,
  serialized_end=298,
)
_sym_db.RegisterEnumDescriptor(_OSDINFO_OSDTYPE)


_OSDINFO = _descriptor.Descriptor(
  name='OsdInfo',
  full_name='YrcfAgent.OsdInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='osd_type', full_name='YrcfAgent.OsdInfo.osd_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='osd_id', full_name='YrcfAgent.OsdInfo.osd_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node_name', full_name='YrcfAgent.OsdInfo.node_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node_id', full_name='YrcfAgent.OsdInfo.node_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group_info', full_name='YrcfAgent.OsdInfo.group_info', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='role_info', full_name='YrcfAgent.OsdInfo.role_info', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state_str', full_name='YrcfAgent.OsdInfo.state_str', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pool_name', full_name='YrcfAgent.OsdInfo.pool_name', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='space_info', full_name='YrcfAgent.OsdInfo.space_info', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pool_info', full_name='YrcfAgent.OsdInfo.pool_info', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OSDINFO_OSDTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=298,
)


_LISTOSDSREQUEST = _descriptor.Descriptor(
  name='ListOsdsRequest',
  full_name='YrcfAgent.ListOsdsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='osd_type', full_name='YrcfAgent.ListOsdsRequest.osd_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pool_id', full_name='YrcfAgent.ListOsdsRequest.pool_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=380,
)


_LISTOSDSRESPONSE = _descriptor.Descriptor(
  name='ListOsdsResponse',
  full_name='YrcfAgent.ListOsdsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='YrcfAgent.ListOsdsResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='osd_info_list', full_name='YrcfAgent.ListOsdsResponse.osd_info_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=382,
  serialized_end=478,
)

_OSDINFO.fields_by_name['osd_type'].enum_type = _OSDINFO_OSDTYPE
_OSDINFO_OSDTYPE.containing_type = _OSDINFO
_LISTOSDSREQUEST.fields_by_name['osd_type'].enum_type = _OSDINFO_OSDTYPE
_LISTOSDSRESPONSE.fields_by_name['result'].message_type = response__pb2._RESMES
_LISTOSDSRESPONSE.fields_by_name['osd_info_list'].message_type = _OSDINFO
DESCRIPTOR.message_types_by_name['OsdInfo'] = _OSDINFO
DESCRIPTOR.message_types_by_name['ListOsdsRequest'] = _LISTOSDSREQUEST
DESCRIPTOR.message_types_by_name['ListOsdsResponse'] = _LISTOSDSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OsdInfo = _reflection.GeneratedProtocolMessageType('OsdInfo', (_message.Message,), dict(
  DESCRIPTOR = _OSDINFO,
  __module__ = 'listosds_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.OsdInfo)
  ))
_sym_db.RegisterMessage(OsdInfo)

ListOsdsRequest = _reflection.GeneratedProtocolMessageType('ListOsdsRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTOSDSREQUEST,
  __module__ = 'listosds_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.ListOsdsRequest)
  ))
_sym_db.RegisterMessage(ListOsdsRequest)

ListOsdsResponse = _reflection.GeneratedProtocolMessageType('ListOsdsResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTOSDSRESPONSE,
  __module__ = 'listosds_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.ListOsdsResponse)
  ))
_sym_db.RegisterMessage(ListOsdsResponse)



_LISTOSDS = _descriptor.ServiceDescriptor(
  name='ListOsds',
  full_name='YrcfAgent.ListOsds',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=480,
  serialized_end=561,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListOsds',
    full_name='YrcfAgent.ListOsds.ListOsds',
    index=0,
    containing_service=None,
    input_type=_LISTOSDSREQUEST,
    output_type=_LISTOSDSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LISTOSDS)

DESCRIPTOR.services_by_name['ListOsds'] = _LISTOSDS

# @@protoc_insertion_point(module_scope)
