# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import listdir_pb2 as listdir__pb2


class ListDirStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDir = channel.unary_unary(
                '/YrcfAgent.ListDir/ListDir',
                request_serializer=listdir__pb2.ListDirPara.SerializeToString,
                response_deserializer=listdir__pb2.ListDirResponse.FromString,
                )


class ListDirServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListDir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ListDirServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDir': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDir,
                    request_deserializer=listdir__pb2.ListDirPara.FromString,
                    response_serializer=listdir__pb2.ListDirResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'YrcfAgent.ListDir', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ListDir(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/YrcfAgent.ListDir/ListDir',
            listdir__pb2.ListDirPara.SerializeToString,
            listdir__pb2.ListDirResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
