# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import listosds_pb2 as listosds__pb2


class ListOsdsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListOsds = channel.unary_unary(
                '/YrcfAgent.ListOsds/ListOsds',
                request_serializer=listosds__pb2.ListOsdsRequest.SerializeToString,
                response_deserializer=listosds__pb2.ListOsdsResponse.FromString,
                )


class ListOsdsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListOsds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ListOsdsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListOsds': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOsds,
                    request_deserializer=listosds__pb2.ListOsdsRequest.FromString,
                    response_serializer=listosds__pb2.ListOsdsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'YrcfAgent.ListOsds', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ListOsds(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListOsds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/YrcfAgent.ListOsds/ListOsds',
            listosds__pb2.ListOsdsRequest.SerializeToString,
            listosds__pb2.ListOsdsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
