# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mdsoverview_pb2 as mdsoverview__pb2


class MdsOverviewStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MdsOverview = channel.unary_unary(
                '/YrcfAgent.MdsOverview/MdsOverview',
                request_serializer=mdsoverview__pb2.MdsOverviewPara.SerializeToString,
                response_deserializer=mdsoverview__pb2.MdsOverviewResponse.FromString,
                )


class MdsOverviewServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MdsOverview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MdsOverviewServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MdsOverview': grpc.unary_unary_rpc_method_handler(
                    servicer.MdsOverview,
                    request_deserializer=mdsoverview__pb2.MdsOverviewPara.FromString,
                    response_serializer=mdsoverview__pb2.MdsOverviewResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'YrcfAgent.MdsOverview', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MdsOverview(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MdsOverview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/YrcfAgent.MdsOverview/MdsOverview',
            mdsoverview__pb2.MdsOverviewPara.SerializeToString,
            mdsoverview__pb2.MdsOverviewResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
