# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mkdir.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import response_pb2 as response__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mkdir.proto',
  package='YrcfAgent',
  syntax='proto3',
  serialized_pb=_b('\n\x0bmkdir.proto\x12\tYrcfAgent\x1a\x0eresponse.proto\"\xa4\x01\n\x0cMkDirRequest\x12\x19\n\x11use_absolute_path\x18\x01 \x01(\x08\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x12\n\nprefer_mds\x18\x03 \x01(\t\x12\x13\n\x0b\x61\x63\x63\x65ss_mode\x18\x04 \x01(\t\x12\x0b\n\x03uid\x18\x05 \x01(\x04\x12\x0b\n\x03gid\x18\x06 \x01(\x04\x12\x16\n\x0enot_use_mirror\x18\x07 \x01(\x08\x12\x10\n\x08\x63\x61sefold\x18\x08 \x01(\x08\"2\n\rMkDirResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes2E\n\x05MkDir\x12<\n\x05MkDir\x12\x17.YrcfAgent.MkDirRequest\x1a\x18.YrcfAgent.MkDirResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[response__pb2.DESCRIPTOR,])




_MKDIRREQUEST = _descriptor.Descriptor(
  name='MkDirRequest',
  full_name='YrcfAgent.MkDirRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='use_absolute_path', full_name='YrcfAgent.MkDirRequest.use_absolute_path', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='YrcfAgent.MkDirRequest.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prefer_mds', full_name='YrcfAgent.MkDirRequest.prefer_mds', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='access_mode', full_name='YrcfAgent.MkDirRequest.access_mode', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='YrcfAgent.MkDirRequest.uid', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gid', full_name='YrcfAgent.MkDirRequest.gid', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='not_use_mirror', full_name='YrcfAgent.MkDirRequest.not_use_mirror', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='casefold', full_name='YrcfAgent.MkDirRequest.casefold', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=207,
)


_MKDIRRESPONSE = _descriptor.Descriptor(
  name='MkDirResponse',
  full_name='YrcfAgent.MkDirResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='YrcfAgent.MkDirResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=259,
)

_MKDIRRESPONSE.fields_by_name['result'].message_type = response__pb2._RESMES
DESCRIPTOR.message_types_by_name['MkDirRequest'] = _MKDIRREQUEST
DESCRIPTOR.message_types_by_name['MkDirResponse'] = _MKDIRRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MkDirRequest = _reflection.GeneratedProtocolMessageType('MkDirRequest', (_message.Message,), dict(
  DESCRIPTOR = _MKDIRREQUEST,
  __module__ = 'mkdir_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.MkDirRequest)
  ))
_sym_db.RegisterMessage(MkDirRequest)

MkDirResponse = _reflection.GeneratedProtocolMessageType('MkDirResponse', (_message.Message,), dict(
  DESCRIPTOR = _MKDIRRESPONSE,
  __module__ = 'mkdir_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.MkDirResponse)
  ))
_sym_db.RegisterMessage(MkDirResponse)



_MKDIR = _descriptor.ServiceDescriptor(
  name='MkDir',
  full_name='YrcfAgent.MkDir',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=261,
  serialized_end=330,
  methods=[
  _descriptor.MethodDescriptor(
    name='MkDir',
    full_name='YrcfAgent.MkDir.MkDir',
    index=0,
    containing_service=None,
    input_type=_MKDIRREQUEST,
    output_type=_MKDIRRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MKDIR)

DESCRIPTOR.services_by_name['MkDir'] = _MKDIR

# @@protoc_insertion_point(module_scope)
