# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

#import mkfs_pb2 as mkfs__pb2
from . import mkfs_pb2 as mkfs__pb2


class MkfsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Mkfs = channel.unary_unary(
        '/YrcfAgent.Mkfs/Mkfs',
        request_serializer=mkfs__pb2.MkfsRequest.SerializeToString,
        response_deserializer=mkfs__pb2.MkfsResponse.FromString,
        )


class MkfsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Mkfs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MkfsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Mkfs': grpc.unary_unary_rpc_method_handler(
          servicer.Mkfs,
          request_deserializer=mkfs__pb2.MkfsRequest.FromString,
          response_serializer=mkfs__pb2.MkfsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'YrcfAgent.Mkfs', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
