# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mkfs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mkfs.proto',
  package='YrcfAgent',
  syntax='proto3',
  serialized_pb=_b('\n\nmkfs.proto\x12\tYrcfAgent\x1a\x0eresponse.proto\"\r\n\x0bMkfsRequest\"1\n\x0cMkfsResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes2A\n\x04Mkfs\x12\x39\n\x04Mkfs\x12\x16.YrcfAgent.MkfsRequest\x1a\x17.YrcfAgent.MkfsResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[response__pb2.DESCRIPTOR,])




_MKFSREQUEST = _descriptor.Descriptor(
  name='MkfsRequest',
  full_name='YrcfAgent.MkfsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=54,
)


_MKFSRESPONSE = _descriptor.Descriptor(
  name='MkfsResponse',
  full_name='YrcfAgent.MkfsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='YrcfAgent.MkfsResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=105,
)

_MKFSRESPONSE.fields_by_name['result'].message_type = response__pb2._RESMES
DESCRIPTOR.message_types_by_name['MkfsRequest'] = _MKFSREQUEST
DESCRIPTOR.message_types_by_name['MkfsResponse'] = _MKFSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MkfsRequest = _reflection.GeneratedProtocolMessageType('MkfsRequest', (_message.Message,), dict(
  DESCRIPTOR = _MKFSREQUEST,
  __module__ = 'mkfs_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.MkfsRequest)
  ))
_sym_db.RegisterMessage(MkfsRequest)

MkfsResponse = _reflection.GeneratedProtocolMessageType('MkfsResponse', (_message.Message,), dict(
  DESCRIPTOR = _MKFSRESPONSE,
  __module__ = 'mkfs_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.MkfsResponse)
  ))
_sym_db.RegisterMessage(MkfsResponse)



_MKFS = _descriptor.ServiceDescriptor(
  name='Mkfs',
  full_name='YrcfAgent.Mkfs',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=107,
  serialized_end=172,
  methods=[
  _descriptor.MethodDescriptor(
    name='Mkfs',
    full_name='YrcfAgent.Mkfs.Mkfs',
    index=0,
    containing_service=None,
    input_type=_MKFSREQUEST,
    output_type=_MKFSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MKFS)

DESCRIPTOR.services_by_name['Mkfs'] = _MKFS

# @@protoc_insertion_point(module_scope)
