# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mkfs_pb2 as mkfs__pb2


class MkfsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Mkfs = channel.unary_unary(
                '/YrcfAgent.Mkfs/Mkfs',
                request_serializer=mkfs__pb2.MkfsRequest.SerializeToString,
                response_deserializer=mkfs__pb2.MkfsResponse.FromString,
                )


class MkfsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Mkfs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MkfsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Mkfs': grpc.unary_unary_rpc_method_handler(
                    servicer.Mkfs,
                    request_deserializer=mkfs__pb2.MkfsRequest.FromString,
                    response_serializer=mkfs__pb2.MkfsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'YrcfAgent.Mkfs', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Mkfs(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Mkfs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/YrcfAgent.Mkfs/Mkfs',
            mkfs__pb2.MkfsRequest.SerializeToString,
            mkfs__pb2.MkfsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
