# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mkfs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmkfs.proto\x12\tYrcfAgent\x1a\x0eresponse.proto\"\r\n\x0bMkfsRequest\"1\n\x0cMkfsResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes2A\n\x04Mkfs\x12\x39\n\x04Mkfs\x12\x16.YrcfAgent.MkfsRequest\x1a\x17.YrcfAgent.MkfsResponse\"\x00\x62\x06proto3')



_MKFSREQUEST = DESCRIPTOR.message_types_by_name['MkfsRequest']
_MKFSRESPONSE = DESCRIPTOR.message_types_by_name['MkfsResponse']
MkfsRequest = _reflection.GeneratedProtocolMessageType('MkfsRequest', (_message.Message,), {
  'DESCRIPTOR' : _MKFSREQUEST,
  '__module__' : 'mkfs_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.MkfsRequest)
  })
_sym_db.RegisterMessage(MkfsRequest)

MkfsResponse = _reflection.GeneratedProtocolMessageType('MkfsResponse', (_message.Message,), {
  'DESCRIPTOR' : _MKFSRESPONSE,
  '__module__' : 'mkfs_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.MkfsResponse)
  })
_sym_db.RegisterMessage(MkfsResponse)

_MKFS = DESCRIPTOR.services_by_name['Mkfs']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MKFSREQUEST._serialized_start=41
  _MKFSREQUEST._serialized_end=54
  _MKFSRESPONSE._serialized_start=56
  _MKFSRESPONSE._serialized_end=105
  _MKFS._serialized_start=107
  _MKFS._serialized_end=172
# @@protoc_insertion_point(module_scope)
