# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nodeoverview.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12nodeoverview.proto\x12\tYrcfAgent\"(\n\tTimeValue\x12\x0c\n\x04time\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\x04\"D\n\nServerNode\x12\x11\n\tnode_name\x18\x01 \x01(\t\x12\x13\n\x0bnode_num_id\x18\x02 \x01(\r\x12\x0e\n\x06online\x18\x03 \x01(\x08\x62\x06proto3')



_TIMEVALUE = DESCRIPTOR.message_types_by_name['TimeValue']
_SERVERNODE = DESCRIPTOR.message_types_by_name['ServerNode']
TimeValue = _reflection.GeneratedProtocolMessageType('TimeValue', (_message.Message,), {
  'DESCRIPTOR' : _TIMEVALUE,
  '__module__' : 'nodeoverview_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.TimeValue)
  })
_sym_db.RegisterMessage(TimeValue)

ServerNode = _reflection.GeneratedProtocolMessageType('ServerNode', (_message.Message,), {
  'DESCRIPTOR' : _SERVERNODE,
  '__module__' : 'nodeoverview_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.ServerNode)
  })
_sym_db.RegisterMessage(ServerNode)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIMEVALUE._serialized_start=33
  _TIMEVALUE._serialized_end=73
  _SERVERNODE._serialized_start=75
  _SERVERNODE._serialized_end=143
# @@protoc_insertion_point(module_scope)
