# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nodeoverview.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nodeoverview.proto',
  package='YrcfAgent',
  syntax='proto3',
  serialized_pb=_b('\n\x12nodeoverview.proto\x12\tYrcfAgent\"(\n\tTimeValue\x12\x0c\n\x04time\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\x04\"D\n\nServerNode\x12\x11\n\tnode_name\x18\x01 \x01(\t\x12\x13\n\x0bnode_num_id\x18\x02 \x01(\r\x12\x0e\n\x06online\x18\x03 \x01(\x08\x62\x06proto3')
)




_TIMEVALUE = _descriptor.Descriptor(
  name='TimeValue',
  full_name='YrcfAgent.TimeValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='YrcfAgent.TimeValue.time', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='YrcfAgent.TimeValue.value', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=73,
)


_SERVERNODE = _descriptor.Descriptor(
  name='ServerNode',
  full_name='YrcfAgent.ServerNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_name', full_name='YrcfAgent.ServerNode.node_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node_num_id', full_name='YrcfAgent.ServerNode.node_num_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='online', full_name='YrcfAgent.ServerNode.online', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=143,
)

DESCRIPTOR.message_types_by_name['TimeValue'] = _TIMEVALUE
DESCRIPTOR.message_types_by_name['ServerNode'] = _SERVERNODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimeValue = _reflection.GeneratedProtocolMessageType('TimeValue', (_message.Message,), dict(
  DESCRIPTOR = _TIMEVALUE,
  __module__ = 'nodeoverview_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.TimeValue)
  ))
_sym_db.RegisterMessage(TimeValue)

ServerNode = _reflection.GeneratedProtocolMessageType('ServerNode', (_message.Message,), dict(
  DESCRIPTOR = _SERVERNODE,
  __module__ = 'nodeoverview_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.ServerNode)
  ))
_sym_db.RegisterMessage(ServerNode)


# @@protoc_insertion_point(module_scope)
