# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ossoverview.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nodeoverview_pb2 as nodeoverview__pb2
import response_pb2 as response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ossoverview.proto\x12\tYrcfAgent\x1a\x12nodeoverview.proto\x1a\x0eresponse.proto\"!\n\x0fOssOverviewPara\x12\x0e\n\x06unused\x18\x01 \x01(\x08\"\xfe\x02\n\x0eOssOverviewRet\x12\x18\n\x10\x64isk_space_total\x18\x01 \x01(\x04\x12\x17\n\x0f\x64isk_space_free\x18\x02 \x01(\x04\x12\x17\n\x0f\x64isk_space_used\x18\x03 \x01(\x04\x12\x15\n\rdisk_read_sum\x18\x04 \x01(\x04\x12\x16\n\x0e\x64isk_write_sum\x18\x05 \x01(\x04\x12(\n\tnode_info\x18\x06 \x03(\x0b\x32\x15.YrcfAgent.ServerNode\x12,\n\x0e\x64isk_perf_read\x18\x07 \x03(\x0b\x32\x14.YrcfAgent.TimeValue\x12\x34\n\x16\x64isk_perf_average_read\x18\x08 \x03(\x0b\x32\x14.YrcfAgent.TimeValue\x12-\n\x0f\x64isk_perf_write\x18\t \x03(\x0b\x32\x14.YrcfAgent.TimeValue\x12\x34\n\x16\x64isk_per_average_write\x18\n \x03(\x0b\x32\x14.YrcfAgent.TimeValue\"b\n\x13OssOverviewResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.YrcfAgent.OssOverviewRet2Z\n\x0bOssOverview\x12K\n\x0bOssOverview\x12\x1a.YrcfAgent.OssOverviewPara\x1a\x1e.YrcfAgent.OssOverviewResponse\"\x00\x62\x06proto3')



_OSSOVERVIEWPARA = DESCRIPTOR.message_types_by_name['OssOverviewPara']
_OSSOVERVIEWRET = DESCRIPTOR.message_types_by_name['OssOverviewRet']
_OSSOVERVIEWRESPONSE = DESCRIPTOR.message_types_by_name['OssOverviewResponse']
OssOverviewPara = _reflection.GeneratedProtocolMessageType('OssOverviewPara', (_message.Message,), {
  'DESCRIPTOR' : _OSSOVERVIEWPARA,
  '__module__' : 'ossoverview_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.OssOverviewPara)
  })
_sym_db.RegisterMessage(OssOverviewPara)

OssOverviewRet = _reflection.GeneratedProtocolMessageType('OssOverviewRet', (_message.Message,), {
  'DESCRIPTOR' : _OSSOVERVIEWRET,
  '__module__' : 'ossoverview_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.OssOverviewRet)
  })
_sym_db.RegisterMessage(OssOverviewRet)

OssOverviewResponse = _reflection.GeneratedProtocolMessageType('OssOverviewResponse', (_message.Message,), {
  'DESCRIPTOR' : _OSSOVERVIEWRESPONSE,
  '__module__' : 'ossoverview_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.OssOverviewResponse)
  })
_sym_db.RegisterMessage(OssOverviewResponse)

_OSSOVERVIEW = DESCRIPTOR.services_by_name['OssOverview']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OSSOVERVIEWPARA._serialized_start=68
  _OSSOVERVIEWPARA._serialized_end=101
  _OSSOVERVIEWRET._serialized_start=104
  _OSSOVERVIEWRET._serialized_end=486
  _OSSOVERVIEWRESPONSE._serialized_start=488
  _OSSOVERVIEWRESPONSE._serialized_end=586
  _OSSOVERVIEW._serialized_start=588
  _OSSOVERVIEW._serialized_end=678
# @@protoc_insertion_point(module_scope)
