# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ossoverview.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nodeoverview_pb2 as nodeoverview__pb2
import response_pb2 as response__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ossoverview.proto',
  package='YrcfAgent',
  syntax='proto3',
  serialized_pb=_b('\n\x11ossoverview.proto\x12\tYrcfAgent\x1a\x12nodeoverview.proto\x1a\x0eresponse.proto\"!\n\x0fOssOverviewPara\x12\x0e\n\x06unused\x18\x01 \x01(\x08\"\xfe\x02\n\x0eOssOverviewRet\x12\x18\n\x10\x64isk_space_total\x18\x01 \x01(\x04\x12\x17\n\x0f\x64isk_space_free\x18\x02 \x01(\x04\x12\x17\n\x0f\x64isk_space_used\x18\x03 \x01(\x04\x12\x15\n\rdisk_read_sum\x18\x04 \x01(\x04\x12\x16\n\x0e\x64isk_write_sum\x18\x05 \x01(\x04\x12(\n\tnode_info\x18\x06 \x03(\x0b\x32\x15.YrcfAgent.ServerNode\x12,\n\x0e\x64isk_perf_read\x18\x07 \x03(\x0b\x32\x14.YrcfAgent.TimeValue\x12\x34\n\x16\x64isk_perf_average_read\x18\x08 \x03(\x0b\x32\x14.YrcfAgent.TimeValue\x12-\n\x0f\x64isk_perf_write\x18\t \x03(\x0b\x32\x14.YrcfAgent.TimeValue\x12\x34\n\x16\x64isk_per_average_write\x18\n \x03(\x0b\x32\x14.YrcfAgent.TimeValue\"b\n\x13OssOverviewResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.YrcfAgent.OssOverviewRet2Z\n\x0bOssOverview\x12K\n\x0bOssOverview\x12\x1a.YrcfAgent.OssOverviewPara\x1a\x1e.YrcfAgent.OssOverviewResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[nodeoverview__pb2.DESCRIPTOR,response__pb2.DESCRIPTOR,])




_OSSOVERVIEWPARA = _descriptor.Descriptor(
  name='OssOverviewPara',
  full_name='YrcfAgent.OssOverviewPara',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unused', full_name='YrcfAgent.OssOverviewPara.unused', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=101,
)


_OSSOVERVIEWRET = _descriptor.Descriptor(
  name='OssOverviewRet',
  full_name='YrcfAgent.OssOverviewRet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='disk_space_total', full_name='YrcfAgent.OssOverviewRet.disk_space_total', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disk_space_free', full_name='YrcfAgent.OssOverviewRet.disk_space_free', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disk_space_used', full_name='YrcfAgent.OssOverviewRet.disk_space_used', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disk_read_sum', full_name='YrcfAgent.OssOverviewRet.disk_read_sum', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disk_write_sum', full_name='YrcfAgent.OssOverviewRet.disk_write_sum', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node_info', full_name='YrcfAgent.OssOverviewRet.node_info', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disk_perf_read', full_name='YrcfAgent.OssOverviewRet.disk_perf_read', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disk_perf_average_read', full_name='YrcfAgent.OssOverviewRet.disk_perf_average_read', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disk_perf_write', full_name='YrcfAgent.OssOverviewRet.disk_perf_write', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disk_per_average_write', full_name='YrcfAgent.OssOverviewRet.disk_per_average_write', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=486,
)


_OSSOVERVIEWRESPONSE = _descriptor.Descriptor(
  name='OssOverviewResponse',
  full_name='YrcfAgent.OssOverviewResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='YrcfAgent.OssOverviewResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='YrcfAgent.OssOverviewResponse.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=488,
  serialized_end=586,
)

_OSSOVERVIEWRET.fields_by_name['node_info'].message_type = nodeoverview__pb2._SERVERNODE
_OSSOVERVIEWRET.fields_by_name['disk_perf_read'].message_type = nodeoverview__pb2._TIMEVALUE
_OSSOVERVIEWRET.fields_by_name['disk_perf_average_read'].message_type = nodeoverview__pb2._TIMEVALUE
_OSSOVERVIEWRET.fields_by_name['disk_perf_write'].message_type = nodeoverview__pb2._TIMEVALUE
_OSSOVERVIEWRET.fields_by_name['disk_per_average_write'].message_type = nodeoverview__pb2._TIMEVALUE
_OSSOVERVIEWRESPONSE.fields_by_name['result'].message_type = response__pb2._RESMES
_OSSOVERVIEWRESPONSE.fields_by_name['value'].message_type = _OSSOVERVIEWRET
DESCRIPTOR.message_types_by_name['OssOverviewPara'] = _OSSOVERVIEWPARA
DESCRIPTOR.message_types_by_name['OssOverviewRet'] = _OSSOVERVIEWRET
DESCRIPTOR.message_types_by_name['OssOverviewResponse'] = _OSSOVERVIEWRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OssOverviewPara = _reflection.GeneratedProtocolMessageType('OssOverviewPara', (_message.Message,), dict(
  DESCRIPTOR = _OSSOVERVIEWPARA,
  __module__ = 'ossoverview_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.OssOverviewPara)
  ))
_sym_db.RegisterMessage(OssOverviewPara)

OssOverviewRet = _reflection.GeneratedProtocolMessageType('OssOverviewRet', (_message.Message,), dict(
  DESCRIPTOR = _OSSOVERVIEWRET,
  __module__ = 'ossoverview_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.OssOverviewRet)
  ))
_sym_db.RegisterMessage(OssOverviewRet)

OssOverviewResponse = _reflection.GeneratedProtocolMessageType('OssOverviewResponse', (_message.Message,), dict(
  DESCRIPTOR = _OSSOVERVIEWRESPONSE,
  __module__ = 'ossoverview_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.OssOverviewResponse)
  ))
_sym_db.RegisterMessage(OssOverviewResponse)



_OSSOVERVIEW = _descriptor.ServiceDescriptor(
  name='OssOverview',
  full_name='YrcfAgent.OssOverview',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=588,
  serialized_end=678,
  methods=[
  _descriptor.MethodDescriptor(
    name='OssOverview',
    full_name='YrcfAgent.OssOverview.OssOverview',
    index=0,
    containing_service=None,
    input_type=_OSSOVERVIEWPARA,
    output_type=_OSSOVERVIEWRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_OSSOVERVIEW)

DESCRIPTOR.services_by_name['OssOverview'] = _OSSOVERVIEW

# @@protoc_insertion_point(module_scope)
