# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ossoverview_pb2 as ossoverview__pb2


class OssOverviewStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.OssOverview = channel.unary_unary(
        '/YrcfAgent.OssOverview/OssOverview',
        request_serializer=ossoverview__pb2.OssOverviewPara.SerializeToString,
        response_deserializer=ossoverview__pb2.OssOverviewResponse.FromString,
        )


class OssOverviewServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def OssOverview(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OssOverviewServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'OssOverview': grpc.unary_unary_rpc_method_handler(
          servicer.OssOverview,
          request_deserializer=ossoverview__pb2.OssOverviewPara.FromString,
          response_serializer=ossoverview__pb2.OssOverviewResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'YrcfAgent.OssOverview', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
