# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import projectquota_pb2 as projectquota__pb2


class ProjectQuotaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddProjectQuota = channel.unary_unary(
                '/YrcfAgent.ProjectQuota/AddProjectQuota',
                request_serializer=projectquota__pb2.AddProjectQuotaPara.SerializeToString,
                response_deserializer=projectquota__pb2.AddProjectQuotaResponse.FromString,
                )
        self.ListProjectQuota = channel.unary_unary(
                '/YrcfAgent.ProjectQuota/ListProjectQuota',
                request_serializer=projectquota__pb2.ListProjectQuotaPara.SerializeToString,
                response_deserializer=projectquota__pb2.ListProjectQuotaResponse.FromString,
                )
        self.DeleteProjectQuota = channel.unary_unary(
                '/YrcfAgent.ProjectQuota/DeleteProjectQuota',
                request_serializer=projectquota__pb2.DeleteProjectQuotaPara.SerializeToString,
                response_deserializer=projectquota__pb2.DeleteProjectQuotaResponse.FromString,
                )
        self.UpdateProjectQuota = channel.unary_unary(
                '/YrcfAgent.ProjectQuota/UpdateProjectQuota',
                request_serializer=projectquota__pb2.UpdateProjectQuotaPara.SerializeToString,
                response_deserializer=projectquota__pb2.UpdateProjectQuotaResponse.FromString,
                )


class ProjectQuotaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddProjectQuota(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProjectQuota(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProjectQuota(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProjectQuota(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProjectQuotaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddProjectQuota': grpc.unary_unary_rpc_method_handler(
                    servicer.AddProjectQuota,
                    request_deserializer=projectquota__pb2.AddProjectQuotaPara.FromString,
                    response_serializer=projectquota__pb2.AddProjectQuotaResponse.SerializeToString,
            ),
            'ListProjectQuota': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProjectQuota,
                    request_deserializer=projectquota__pb2.ListProjectQuotaPara.FromString,
                    response_serializer=projectquota__pb2.ListProjectQuotaResponse.SerializeToString,
            ),
            'DeleteProjectQuota': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProjectQuota,
                    request_deserializer=projectquota__pb2.DeleteProjectQuotaPara.FromString,
                    response_serializer=projectquota__pb2.DeleteProjectQuotaResponse.SerializeToString,
            ),
            'UpdateProjectQuota': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProjectQuota,
                    request_deserializer=projectquota__pb2.UpdateProjectQuotaPara.FromString,
                    response_serializer=projectquota__pb2.UpdateProjectQuotaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'YrcfAgent.ProjectQuota', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProjectQuota(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddProjectQuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/YrcfAgent.ProjectQuota/AddProjectQuota',
            projectquota__pb2.AddProjectQuotaPara.SerializeToString,
            projectquota__pb2.AddProjectQuotaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListProjectQuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/YrcfAgent.ProjectQuota/ListProjectQuota',
            projectquota__pb2.ListProjectQuotaPara.SerializeToString,
            projectquota__pb2.ListProjectQuotaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteProjectQuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/YrcfAgent.ProjectQuota/DeleteProjectQuota',
            projectquota__pb2.DeleteProjectQuotaPara.SerializeToString,
            projectquota__pb2.DeleteProjectQuotaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateProjectQuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/YrcfAgent.ProjectQuota/UpdateProjectQuota',
            projectquota__pb2.UpdateProjectQuotaPara.SerializeToString,
            projectquota__pb2.UpdateProjectQuotaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
