# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import qos_pb2 as qos__pb2


class QosStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddQos = channel.unary_unary(
                '/YrcfAgent.Qos/AddQos',
                request_serializer=qos__pb2.AddQosPara.SerializeToString,
                response_deserializer=qos__pb2.AddQosResponse.FromString,
                )
        self.DeleteQos = channel.unary_unary(
                '/YrcfAgent.Qos/DeleteQos',
                request_serializer=qos__pb2.DeleteQosPara.SerializeToString,
                response_deserializer=qos__pb2.DeleteQosResponse.FromString,
                )
        self.ListQos = channel.unary_unary(
                '/YrcfAgent.Qos/ListQos',
                request_serializer=qos__pb2.ListQosPara.SerializeToString,
                response_deserializer=qos__pb2.ListQosResponse.FromString,
                )


class QosServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddQos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteQos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListQos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QosServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddQos': grpc.unary_unary_rpc_method_handler(
                    servicer.AddQos,
                    request_deserializer=qos__pb2.AddQosPara.FromString,
                    response_serializer=qos__pb2.AddQosResponse.SerializeToString,
            ),
            'DeleteQos': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteQos,
                    request_deserializer=qos__pb2.DeleteQosPara.FromString,
                    response_serializer=qos__pb2.DeleteQosResponse.SerializeToString,
            ),
            'ListQos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListQos,
                    request_deserializer=qos__pb2.ListQosPara.FromString,
                    response_serializer=qos__pb2.ListQosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'YrcfAgent.Qos', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Qos(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddQos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/YrcfAgent.Qos/AddQos',
            qos__pb2.AddQosPara.SerializeToString,
            qos__pb2.AddQosResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteQos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/YrcfAgent.Qos/DeleteQos',
            qos__pb2.DeleteQosPara.SerializeToString,
            qos__pb2.DeleteQosResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListQos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/YrcfAgent.Qos/ListQos',
            qos__pb2.ListQosPara.SerializeToString,
            qos__pb2.ListQosResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
