# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='qos.proto',
  package='YrcfAgent',
  syntax='proto3',
  serialized_pb=_b('\n\tqos.proto\x12\tYrcfAgent\x1a\x0eresponse.proto\"\x7f\n\nAddQosPara\x12\x0c\n\x04rbps\x18\x01 \x01(\x04\x12\x0c\n\x04wbps\x18\x02 \x01(\x04\x12\r\n\x05riops\x18\x03 \x01(\x04\x12\r\n\x05wiops\x18\x04 \x01(\x04\x12\x0c\n\x04tbps\x18\x05 \x01(\x04\x12\r\n\x05tiops\x18\x06 \x01(\x04\x12\x0c\n\x04mops\x18\x07 \x01(\x04\x12\x0c\n\x04path\x18\x08 \x01(\t\"3\n\x0e\x41\x64\x64QosResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes\"+\n\x0bListQosPara\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0e\n\x06prefix\x18\x02 \x01(\x08\"\x89\x01\n\x07QosInfo\x12\x0b\n\x03\x65id\x18\x01 \x01(\t\x12\x0c\n\x04rbps\x18\x02 \x01(\x04\x12\x0c\n\x04wbps\x18\x03 \x01(\x04\x12\r\n\x05riops\x18\x04 \x01(\x04\x12\r\n\x05wiops\x18\x05 \x01(\x04\x12\x0c\n\x04tbps\x18\x06 \x01(\x04\x12\r\n\x05tiops\x18\x07 \x01(\x04\x12\x0c\n\x04mops\x18\x08 \x01(\x04\x12\x0c\n\x04path\x18\t \x01(\t\"7\n\nQosInfoRet\x12)\n\rqos_info_list\x18\x01 \x03(\x0b\x32\x12.YrcfAgent.QosInfo\"Z\n\x0fListQosResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.YrcfAgent.QosInfoRet\"?\n\rDeleteQosPara\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x11\n\trecursive\x18\x02 \x01(\x08\x12\r\n\x05\x66orce\x18\x03 \x01(\x08\"6\n\x11\x44\x65leteQosResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes2\xcb\x01\n\x03Qos\x12<\n\x06\x41\x64\x64Qos\x12\x15.YrcfAgent.AddQosPara\x1a\x19.YrcfAgent.AddQosResponse\"\x00\x12\x45\n\tDeleteQos\x12\x18.YrcfAgent.DeleteQosPara\x1a\x1c.YrcfAgent.DeleteQosResponse\"\x00\x12?\n\x07ListQos\x12\x16.YrcfAgent.ListQosPara\x1a\x1a.YrcfAgent.ListQosResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[response__pb2.DESCRIPTOR,])




_ADDQOSPARA = _descriptor.Descriptor(
  name='AddQosPara',
  full_name='YrcfAgent.AddQosPara',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rbps', full_name='YrcfAgent.AddQosPara.rbps', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wbps', full_name='YrcfAgent.AddQosPara.wbps', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='riops', full_name='YrcfAgent.AddQosPara.riops', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wiops', full_name='YrcfAgent.AddQosPara.wiops', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tbps', full_name='YrcfAgent.AddQosPara.tbps', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tiops', full_name='YrcfAgent.AddQosPara.tiops', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mops', full_name='YrcfAgent.AddQosPara.mops', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='YrcfAgent.AddQosPara.path', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=167,
)


_ADDQOSRESPONSE = _descriptor.Descriptor(
  name='AddQosResponse',
  full_name='YrcfAgent.AddQosResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='YrcfAgent.AddQosResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=220,
)


_LISTQOSPARA = _descriptor.Descriptor(
  name='ListQosPara',
  full_name='YrcfAgent.ListQosPara',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='YrcfAgent.ListQosPara.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prefix', full_name='YrcfAgent.ListQosPara.prefix', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=265,
)


_QOSINFO = _descriptor.Descriptor(
  name='QosInfo',
  full_name='YrcfAgent.QosInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='eid', full_name='YrcfAgent.QosInfo.eid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rbps', full_name='YrcfAgent.QosInfo.rbps', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wbps', full_name='YrcfAgent.QosInfo.wbps', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='riops', full_name='YrcfAgent.QosInfo.riops', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wiops', full_name='YrcfAgent.QosInfo.wiops', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tbps', full_name='YrcfAgent.QosInfo.tbps', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tiops', full_name='YrcfAgent.QosInfo.tiops', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mops', full_name='YrcfAgent.QosInfo.mops', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='YrcfAgent.QosInfo.path', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=405,
)


_QOSINFORET = _descriptor.Descriptor(
  name='QosInfoRet',
  full_name='YrcfAgent.QosInfoRet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='qos_info_list', full_name='YrcfAgent.QosInfoRet.qos_info_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=462,
)


_LISTQOSRESPONSE = _descriptor.Descriptor(
  name='ListQosResponse',
  full_name='YrcfAgent.ListQosResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='YrcfAgent.ListQosResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='YrcfAgent.ListQosResponse.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=464,
  serialized_end=554,
)


_DELETEQOSPARA = _descriptor.Descriptor(
  name='DeleteQosPara',
  full_name='YrcfAgent.DeleteQosPara',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='YrcfAgent.DeleteQosPara.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recursive', full_name='YrcfAgent.DeleteQosPara.recursive', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='force', full_name='YrcfAgent.DeleteQosPara.force', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=556,
  serialized_end=619,
)


_DELETEQOSRESPONSE = _descriptor.Descriptor(
  name='DeleteQosResponse',
  full_name='YrcfAgent.DeleteQosResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='YrcfAgent.DeleteQosResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=621,
  serialized_end=675,
)

_ADDQOSRESPONSE.fields_by_name['result'].message_type = response__pb2._RESMES
_QOSINFORET.fields_by_name['qos_info_list'].message_type = _QOSINFO
_LISTQOSRESPONSE.fields_by_name['result'].message_type = response__pb2._RESMES
_LISTQOSRESPONSE.fields_by_name['value'].message_type = _QOSINFORET
_DELETEQOSRESPONSE.fields_by_name['result'].message_type = response__pb2._RESMES
DESCRIPTOR.message_types_by_name['AddQosPara'] = _ADDQOSPARA
DESCRIPTOR.message_types_by_name['AddQosResponse'] = _ADDQOSRESPONSE
DESCRIPTOR.message_types_by_name['ListQosPara'] = _LISTQOSPARA
DESCRIPTOR.message_types_by_name['QosInfo'] = _QOSINFO
DESCRIPTOR.message_types_by_name['QosInfoRet'] = _QOSINFORET
DESCRIPTOR.message_types_by_name['ListQosResponse'] = _LISTQOSRESPONSE
DESCRIPTOR.message_types_by_name['DeleteQosPara'] = _DELETEQOSPARA
DESCRIPTOR.message_types_by_name['DeleteQosResponse'] = _DELETEQOSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddQosPara = _reflection.GeneratedProtocolMessageType('AddQosPara', (_message.Message,), dict(
  DESCRIPTOR = _ADDQOSPARA,
  __module__ = 'qos_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.AddQosPara)
  ))
_sym_db.RegisterMessage(AddQosPara)

AddQosResponse = _reflection.GeneratedProtocolMessageType('AddQosResponse', (_message.Message,), dict(
  DESCRIPTOR = _ADDQOSRESPONSE,
  __module__ = 'qos_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.AddQosResponse)
  ))
_sym_db.RegisterMessage(AddQosResponse)

ListQosPara = _reflection.GeneratedProtocolMessageType('ListQosPara', (_message.Message,), dict(
  DESCRIPTOR = _LISTQOSPARA,
  __module__ = 'qos_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.ListQosPara)
  ))
_sym_db.RegisterMessage(ListQosPara)

QosInfo = _reflection.GeneratedProtocolMessageType('QosInfo', (_message.Message,), dict(
  DESCRIPTOR = _QOSINFO,
  __module__ = 'qos_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.QosInfo)
  ))
_sym_db.RegisterMessage(QosInfo)

QosInfoRet = _reflection.GeneratedProtocolMessageType('QosInfoRet', (_message.Message,), dict(
  DESCRIPTOR = _QOSINFORET,
  __module__ = 'qos_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.QosInfoRet)
  ))
_sym_db.RegisterMessage(QosInfoRet)

ListQosResponse = _reflection.GeneratedProtocolMessageType('ListQosResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTQOSRESPONSE,
  __module__ = 'qos_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.ListQosResponse)
  ))
_sym_db.RegisterMessage(ListQosResponse)

DeleteQosPara = _reflection.GeneratedProtocolMessageType('DeleteQosPara', (_message.Message,), dict(
  DESCRIPTOR = _DELETEQOSPARA,
  __module__ = 'qos_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.DeleteQosPara)
  ))
_sym_db.RegisterMessage(DeleteQosPara)

DeleteQosResponse = _reflection.GeneratedProtocolMessageType('DeleteQosResponse', (_message.Message,), dict(
  DESCRIPTOR = _DELETEQOSRESPONSE,
  __module__ = 'qos_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.DeleteQosResponse)
  ))
_sym_db.RegisterMessage(DeleteQosResponse)



_QOS = _descriptor.ServiceDescriptor(
  name='Qos',
  full_name='YrcfAgent.Qos',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=678,
  serialized_end=881,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddQos',
    full_name='YrcfAgent.Qos.AddQos',
    index=0,
    containing_service=None,
    input_type=_ADDQOSPARA,
    output_type=_ADDQOSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteQos',
    full_name='YrcfAgent.Qos.DeleteQos',
    index=1,
    containing_service=None,
    input_type=_DELETEQOSPARA,
    output_type=_DELETEQOSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListQos',
    full_name='YrcfAgent.Qos.ListQos',
    index=2,
    containing_service=None,
    input_type=_LISTQOSPARA,
    output_type=_LISTQOSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_QOS)

DESCRIPTOR.services_by_name['Qos'] = _QOS

# @@protoc_insertion_point(module_scope)
