# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rmdir_pb2 as rmdir__pb2


class RmDirStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RmDir = channel.unary_unary(
                '/YrcfAgent.RmDir/RmDir',
                request_serializer=rmdir__pb2.RmDirRequest.SerializeToString,
                response_deserializer=rmdir__pb2.RmDirResponse.FromString,
                )


class RmDirServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RmDir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RmDirServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RmDir': grpc.unary_unary_rpc_method_handler(
                    servicer.RmDir,
                    request_deserializer=rmdir__pb2.RmDirRequest.FromString,
                    response_serializer=rmdir__pb2.RmDirResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'YrcfAgent.RmDir', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RmDir(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RmDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/YrcfAgent.RmDir/RmDir',
            rmdir__pb2.RmDirRequest.SerializeToString,
            rmdir__pb2.RmDirResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
