# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rmdir.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rmdir.proto',
  package='YrcfAgent',
  syntax='proto3',
  serialized_pb=_b('\n\x0brmdir.proto\x12\tYrcfAgent\x1a\x0eresponse.proto\"S\n\x0cRmDirRequest\x12\x19\n\x11use_absolute_path\x18\x01 \x01(\x08\x12\x1a\n\x12remove_recursively\x18\x02 \x01(\x08\x12\x0c\n\x04path\x18\x03 \x01(\t\"2\n\rRmDirResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes2E\n\x05RmDir\x12<\n\x05RmDir\x12\x17.YrcfAgent.RmDirRequest\x1a\x18.YrcfAgent.RmDirResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[response__pb2.DESCRIPTOR,])




_RMDIRREQUEST = _descriptor.Descriptor(
  name='RmDirRequest',
  full_name='YrcfAgent.RmDirRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='use_absolute_path', full_name='YrcfAgent.RmDirRequest.use_absolute_path', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remove_recursively', full_name='YrcfAgent.RmDirRequest.remove_recursively', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='YrcfAgent.RmDirRequest.path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=125,
)


_RMDIRRESPONSE = _descriptor.Descriptor(
  name='RmDirResponse',
  full_name='YrcfAgent.RmDirResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='YrcfAgent.RmDirResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=177,
)

_RMDIRRESPONSE.fields_by_name['result'].message_type = response__pb2._RESMES
DESCRIPTOR.message_types_by_name['RmDirRequest'] = _RMDIRREQUEST
DESCRIPTOR.message_types_by_name['RmDirResponse'] = _RMDIRRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RmDirRequest = _reflection.GeneratedProtocolMessageType('RmDirRequest', (_message.Message,), dict(
  DESCRIPTOR = _RMDIRREQUEST,
  __module__ = 'rmdir_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.RmDirRequest)
  ))
_sym_db.RegisterMessage(RmDirRequest)

RmDirResponse = _reflection.GeneratedProtocolMessageType('RmDirResponse', (_message.Message,), dict(
  DESCRIPTOR = _RMDIRRESPONSE,
  __module__ = 'rmdir_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.RmDirResponse)
  ))
_sym_db.RegisterMessage(RmDirResponse)



_RMDIR = _descriptor.ServiceDescriptor(
  name='RmDir',
  full_name='YrcfAgent.RmDir',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=179,
  serialized_end=248,
  methods=[
  _descriptor.MethodDescriptor(
    name='RmDir',
    full_name='YrcfAgent.RmDir.RmDir',
    index=0,
    containing_service=None,
    input_type=_RMDIRREQUEST,
    output_type=_RMDIRRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RMDIR)

DESCRIPTOR.services_by_name['RmDir'] = _RMDIR

# @@protoc_insertion_point(module_scope)
