# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

#import rmdir_pb2 as rmdir__pb2
from . import rmdir_pb2 as rmdir__pb2


class RmDirStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RmDir = channel.unary_unary(
        '/YrcfAgent.RmDir/RmDir',
        request_serializer=rmdir__pb2.RmDirRequest.SerializeToString,
        response_deserializer=rmdir__pb2.RmDirResponse.FromString,
        )


class RmDirServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RmDir(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RmDirServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RmDir': grpc.unary_unary_rpc_method_handler(
          servicer.RmDir,
          request_deserializer=rmdir__pb2.RmDirRequest.FromString,
          response_serializer=rmdir__pb2.RmDirResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'YrcfAgent.RmDir', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
