# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: setentry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import response_pb2 as response__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='setentry.proto',
  package='YrcfAgent',
  syntax='proto3',
  serialized_pb=_b('\n\x0esetentry.proto\x12\tYrcfAgent\x1a\x0eresponse.proto\"\xe9\x01\n\x0fSetEntryRequest\x12\x18\n\x10use_mounted_path\x18\x01 \x01(\x08\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x13\n\x0bstripe_size\x18\x03 \x01(\t\x12\x14\n\x0cstripe_count\x18\x04 \x01(\r\x12\x31\n\x06schema\x18\x05 \x01(\x0e\x32!.YrcfAgent.SetEntryRequest.Schema\x12\x0f\n\x07pool_id\x18\x06 \x01(\t\x12\x11\n\tforce_set\x18\x07 \x01(\x08\",\n\x06Schema\x12\n\n\x06MIRROR\x10\x00\x12\t\n\x05RAID0\x10\x01\x12\x0b\n\x07STANDBY\x10\x02\"5\n\x10SetEntryResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes2O\n\x08SetEntry\x12\x43\n\x08SetEntry\x12\x1a.YrcfAgent.SetEntryRequest\x1a\x1b.YrcfAgent.SetEntryResponseb\x06proto3')
  ,
  dependencies=[response__pb2.DESCRIPTOR,])



_SETENTRYREQUEST_SCHEMA = _descriptor.EnumDescriptor(
  name='Schema',
  full_name='YrcfAgent.SetEntryRequest.Schema',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MIRROR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RAID0', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STANDBY', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=235,
  serialized_end=279,
)
_sym_db.RegisterEnumDescriptor(_SETENTRYREQUEST_SCHEMA)


_SETENTRYREQUEST = _descriptor.Descriptor(
  name='SetEntryRequest',
  full_name='YrcfAgent.SetEntryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='use_mounted_path', full_name='YrcfAgent.SetEntryRequest.use_mounted_path', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='YrcfAgent.SetEntryRequest.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stripe_size', full_name='YrcfAgent.SetEntryRequest.stripe_size', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stripe_count', full_name='YrcfAgent.SetEntryRequest.stripe_count', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schema', full_name='YrcfAgent.SetEntryRequest.schema', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pool_id', full_name='YrcfAgent.SetEntryRequest.pool_id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='force_set', full_name='YrcfAgent.SetEntryRequest.force_set', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SETENTRYREQUEST_SCHEMA,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=279,
)


_SETENTRYRESPONSE = _descriptor.Descriptor(
  name='SetEntryResponse',
  full_name='YrcfAgent.SetEntryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='YrcfAgent.SetEntryResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=334,
)

_SETENTRYREQUEST.fields_by_name['schema'].enum_type = _SETENTRYREQUEST_SCHEMA
_SETENTRYREQUEST_SCHEMA.containing_type = _SETENTRYREQUEST
_SETENTRYRESPONSE.fields_by_name['result'].message_type = response__pb2._RESMES
DESCRIPTOR.message_types_by_name['SetEntryRequest'] = _SETENTRYREQUEST
DESCRIPTOR.message_types_by_name['SetEntryResponse'] = _SETENTRYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetEntryRequest = _reflection.GeneratedProtocolMessageType('SetEntryRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETENTRYREQUEST,
  __module__ = 'setentry_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.SetEntryRequest)
  ))
_sym_db.RegisterMessage(SetEntryRequest)

SetEntryResponse = _reflection.GeneratedProtocolMessageType('SetEntryResponse', (_message.Message,), dict(
  DESCRIPTOR = _SETENTRYRESPONSE,
  __module__ = 'setentry_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.SetEntryResponse)
  ))
_sym_db.RegisterMessage(SetEntryResponse)



_SETENTRY = _descriptor.ServiceDescriptor(
  name='SetEntry',
  full_name='YrcfAgent.SetEntry',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=336,
  serialized_end=415,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetEntry',
    full_name='YrcfAgent.SetEntry.SetEntry',
    index=0,
    containing_service=None,
    input_type=_SETENTRYREQUEST,
    output_type=_SETENTRYRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SETENTRY)

DESCRIPTOR.services_by_name['SetEntry'] = _SETENTRY

# @@protoc_insertion_point(module_scope)
