# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

#import sla_pb2 as sla__pb2
from . import sla_pb2 as sla__pb2


class SlaStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SlaInfo = channel.unary_unary(
        '/YrcfAgent.Sla/SlaInfo',
        request_serializer=sla__pb2.SlaPara.SerializeToString,
        response_deserializer=sla__pb2.SlaResponse.FromString,
        )


class SlaServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SlaInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SlaServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SlaInfo': grpc.unary_unary_rpc_method_handler(
          servicer.SlaInfo,
          request_deserializer=sla__pb2.SlaPara.FromString,
          response_serializer=sla__pb2.SlaResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'YrcfAgent.Sla', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
