# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sla.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tsla.proto\x12\tYrcfAgent\x1a\x0eresponse.proto\"\x1c\n\x07SlaPara\x12\x11\n\twith_root\x18\x01 \x01(\x08\"\x8c\x01\n\x08SlaValue\x12\x10\n\x08total_rb\x18\x01 \x01(\x04\x12\x10\n\x08total_wb\x18\x02 \x01(\x04\x12\x10\n\x08total_rs\x18\x03 \x01(\x04\x12\x10\n\x08total_ws\x18\x04 \x01(\x04\x12\x0c\n\x04rbps\x18\x05 \x01(\x04\x12\x0c\n\x04wbps\x18\x06 \x01(\x04\x12\r\n\x05riops\x18\x07 \x01(\x04\x12\r\n\x05wiops\x18\x08 \x01(\x04\"P\n\x06SlaRet\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x10\n\x08\x65ntry_id\x18\x02 \x01(\t\x12&\n\tsla_value\x18\x03 \x03(\x0b\x32\x13.YrcfAgent.SlaValue\"R\n\x0bSlaResponse\x12!\n\x06result\x18\x01 \x01(\x0b\x32\x11.YrcfAgent.ResMes\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.YrcfAgent.SlaRet2>\n\x03Sla\x12\x37\n\x07SlaInfo\x12\x12.YrcfAgent.SlaPara\x1a\x16.YrcfAgent.SlaResponse\"\x00\x62\x06proto3')



_SLAPARA = DESCRIPTOR.message_types_by_name['SlaPara']
_SLAVALUE = DESCRIPTOR.message_types_by_name['SlaValue']
_SLARET = DESCRIPTOR.message_types_by_name['SlaRet']
_SLARESPONSE = DESCRIPTOR.message_types_by_name['SlaResponse']
SlaPara = _reflection.GeneratedProtocolMessageType('SlaPara', (_message.Message,), {
  'DESCRIPTOR' : _SLAPARA,
  '__module__' : 'sla_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.SlaPara)
  })
_sym_db.RegisterMessage(SlaPara)

SlaValue = _reflection.GeneratedProtocolMessageType('SlaValue', (_message.Message,), {
  'DESCRIPTOR' : _SLAVALUE,
  '__module__' : 'sla_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.SlaValue)
  })
_sym_db.RegisterMessage(SlaValue)

SlaRet = _reflection.GeneratedProtocolMessageType('SlaRet', (_message.Message,), {
  'DESCRIPTOR' : _SLARET,
  '__module__' : 'sla_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.SlaRet)
  })
_sym_db.RegisterMessage(SlaRet)

SlaResponse = _reflection.GeneratedProtocolMessageType('SlaResponse', (_message.Message,), {
  'DESCRIPTOR' : _SLARESPONSE,
  '__module__' : 'sla_pb2'
  # @@protoc_insertion_point(class_scope:YrcfAgent.SlaResponse)
  })
_sym_db.RegisterMessage(SlaResponse)

_SLA = DESCRIPTOR.services_by_name['Sla']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SLAPARA._serialized_start=40
  _SLAPARA._serialized_end=68
  _SLAVALUE._serialized_start=71
  _SLAVALUE._serialized_end=211
  _SLARET._serialized_start=213
  _SLARET._serialized_end=293
  _SLARESPONSE._serialized_start=295
  _SLARESPONSE._serialized_end=377
  _SLA._serialized_start=379
  _SLA._serialized_end=441
# @@protoc_insertion_point(module_scope)
