# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sla_pb2 as sla__pb2


class SlaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SlaInfo = channel.unary_unary(
                '/YrcfAgent.Sla/SlaInfo',
                request_serializer=sla__pb2.SlaPara.SerializeToString,
                response_deserializer=sla__pb2.SlaResponse.FromString,
                )


class SlaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SlaInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SlaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SlaInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.SlaInfo,
                    request_deserializer=sla__pb2.SlaPara.FromString,
                    response_serializer=sla__pb2.SlaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'YrcfAgent.Sla', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Sla(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SlaInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/YrcfAgent.Sla/SlaInfo',
            sla__pb2.SlaPara.SerializeToString,
            sla__pb2.SlaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
